// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: telemetry/v1/telemetry.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CollectorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectorId   string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Labels        []*Label               `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorInfo) Reset() {
	*x = CollectorInfo{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorInfo) ProtoMessage() {}

func (x *CollectorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorInfo.ProtoReflect.Descriptor instead.
func (*CollectorInfo) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *CollectorInfo) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *CollectorInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *CollectorInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CollectorInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *CollectorInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *CollectorInfo) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Metric struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value             float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,3,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Labels            []*Label               `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *Metric) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ProcessSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	RssBytes      uint64                 `protobuf:"varint,4,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	IoReadBps     float64                `protobuf:"fixed64,5,opt,name=io_read_bps,json=ioReadBps,proto3" json:"io_read_bps,omitempty"`
	IoWriteBps    float64                `protobuf:"fixed64,6,opt,name=io_write_bps,json=ioWriteBps,proto3" json:"io_write_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessSample) Reset() {
	*x = ProcessSample{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSample) ProtoMessage() {}

func (x *ProcessSample) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSample.ProtoReflect.Descriptor instead.
func (*ProcessSample) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessSample) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessSample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessSample) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessSample) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *ProcessSample) GetIoReadBps() float64 {
	if x != nil {
		return x.IoReadBps
	}
	return 0
}

func (x *ProcessSample) GetIoWriteBps() float64 {
	if x != nil {
		return x.IoWriteBps
	}
	return 0
}

type LogFingerprint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint       string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Count             uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Example           string                 `protobuf:"bytes,3,opt,name=example,proto3" json:"example,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,4,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogFingerprint) Reset() {
	*x = LogFingerprint{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFingerprint) ProtoMessage() {}

func (x *LogFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFingerprint.ProtoReflect.Descriptor instead.
func (*LogFingerprint) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *LogFingerprint) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *LogFingerprint) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LogFingerprint) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *LogFingerprint) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

type TelemetryBatch struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Collector             *CollectorInfo         `protobuf:"bytes,1,opt,name=collector,proto3" json:"collector,omitempty"`
	WallTimeUnixNano      int64                  `protobuf:"varint,2,opt,name=wall_time_unix_nano,json=wallTimeUnixNano,proto3" json:"wall_time_unix_nano,omitempty"`
	MonotonicTimeUnixNano int64                  `protobuf:"varint,3,opt,name=monotonic_time_unix_nano,json=monotonicTimeUnixNano,proto3" json:"monotonic_time_unix_nano,omitempty"`
	Metrics               []*Metric              `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Processes             []*ProcessSample       `protobuf:"bytes,5,rep,name=processes,proto3" json:"processes,omitempty"`
	Logs                  []*LogFingerprint      `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	BatchId               string                 `protobuf:"bytes,7,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *TelemetryBatch) GetCollector() *CollectorInfo {
	if x != nil {
		return x.Collector
	}
	return nil
}

func (x *TelemetryBatch) GetWallTimeUnixNano() int64 {
	if x != nil {
		return x.WallTimeUnixNano
	}
	return 0
}

func (x *TelemetryBatch) GetMonotonicTimeUnixNano() int64 {
	if x != nil {
		return x.MonotonicTimeUnixNano
	}
	return 0
}

func (x *TelemetryBatch) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TelemetryBatch) GetProcesses() []*ProcessSample {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *TelemetryBatch) GetLogs() []*LogFingerprint {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *TelemetryBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *Ack) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

var File_telemetry_v1_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1ctelemetry/v1/telemetry.proto\x12\ftelemetry.v1\"/\n" +
	"\x05Label\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb9\x01\n" +
	"\rCollectorInfo\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12+\n" +
	"\x06labels\x18\x06 \x03(\v2\x13.telemetry.v1.LabelR\x06labels\"\x8f\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12.\n" +
	"\x13timestamp_unix_nano\x18\x03 \x01(\x03R\x11timestampUnixNano\x12+\n" +
	"\x06labels\x18\x04 \x03(\v2\x13.telemetry.v1.LabelR\x06labels\"\xb5\x01\n" +
	"\rProcessSample\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\trss_bytes\x18\x04 \x01(\x04R\brssBytes\x12\x1e\n" +
	"\vio_read_bps\x18\x05 \x01(\x01R\tioReadBps\x12 \n" +
	"\fio_write_bps\x18\x06 \x01(\x01R\n" +
	"ioWriteBps\"\x92\x01\n" +
	"\x0eLogFingerprint\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12\x18\n" +
	"\aexample\x18\x03 \x01(\tR\aexample\x12.\n" +
	"\x13timestamp_unix_nano\x18\x04 \x01(\x03R\x11timestampUnixNano\"\xeb\x02\n" +
	"\x0eTelemetryBatch\x129\n" +
	"\tcollector\x18\x01 \x01(\v2\x1b.telemetry.v1.CollectorInfoR\tcollector\x12-\n" +
	"\x13wall_time_unix_nano\x18\x02 \x01(\x03R\x10wallTimeUnixNano\x127\n" +
	"\x18monotonic_time_unix_nano\x18\x03 \x01(\x03R\x15monotonicTimeUnixNano\x12.\n" +
	"\ametrics\x18\x04 \x03(\v2\x14.telemetry.v1.MetricR\ametrics\x129\n" +
	"\tprocesses\x18\x05 \x03(\v2\x1b.telemetry.v1.ProcessSampleR\tprocesses\x120\n" +
	"\x04logs\x18\x06 \x03(\v2\x1c.telemetry.v1.LogFingerprintR\x04logs\x12\x19\n" +
	"\bbatch_id\x18\a \x01(\tR\abatchId\" \n" +
	"\x03Ack\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId2N\n" +
	"\x0fTelemetryIngest\x12;\n" +
	"\x04Push\x12\x1c.telemetry.v1.TelemetryBatch\x1a\x11.telemetry.v1.Ack(\x010\x01BDZBgithub.com/jfang2048/ai_sre_agent_pub/pkg/telemetry/v1;telemetryv1b\x06proto3"

var (
	file_telemetry_v1_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_v1_telemetry_proto_rawDescData []byte
)

func file_telemetry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)))
	})
	return file_telemetry_v1_telemetry_proto_rawDescData
}

var file_telemetry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_telemetry_v1_telemetry_proto_goTypes = []any{
	(*Label)(nil),          // 0: telemetry.v1.Label
	(*CollectorInfo)(nil),  // 1: telemetry.v1.CollectorInfo
	(*Metric)(nil),         // 2: telemetry.v1.Metric
	(*ProcessSample)(nil),  // 3: telemetry.v1.ProcessSample
	(*LogFingerprint)(nil), // 4: telemetry.v1.LogFingerprint
	(*TelemetryBatch)(nil), // 5: telemetry.v1.TelemetryBatch
	(*Ack)(nil),            // 6: telemetry.v1.Ack
}
var file_telemetry_v1_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.v1.CollectorInfo.labels:type_name -> telemetry.v1.Label
	0, // 1: telemetry.v1.Metric.labels:type_name -> telemetry.v1.Label
	1, // 2: telemetry.v1.TelemetryBatch.collector:type_name -> telemetry.v1.CollectorInfo
	2, // 3: telemetry.v1.TelemetryBatch.metrics:type_name -> telemetry.v1.Metric
	3, // 4: telemetry.v1.TelemetryBatch.processes:type_name -> telemetry.v1.ProcessSample
	4, // 5: telemetry.v1.TelemetryBatch.logs:type_name -> telemetry.v1.LogFingerprint
	5, // 6: telemetry.v1.TelemetryIngest.Push:input_type -> telemetry.v1.TelemetryBatch
	6, // 7: telemetry.v1.TelemetryIngest.Push:output_type -> telemetry.v1.Ack
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_telemetry_v1_telemetry_proto_init() }
func file_telemetry_v1_telemetry_proto_init() {
	if File_telemetry_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_v1_telemetry_proto = out.File
	file_telemetry_v1_telemetry_proto_goTypes = nil
	file_telemetry_v1_telemetry_proto_depIdxs = nil
}
