// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: telemetry/v1/telemetry.proto

package telemetryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryIngest_Push_FullMethodName = "/telemetry.v1.TelemetryIngest/Push"
)

// TelemetryIngestClient is the client API for TelemetryIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryIngestClient interface {
	Push(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryBatch, Ack], error)
}

type telemetryIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryIngestClient(cc grpc.ClientConnInterface) TelemetryIngestClient {
	return &telemetryIngestClient{cc}
}

func (c *telemetryIngestClient) Push(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryBatch, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemetryIngest_ServiceDesc.Streams[0], TelemetryIngest_Push_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryBatch, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryIngest_PushClient = grpc.BidiStreamingClient[TelemetryBatch, Ack]

// TelemetryIngestServer is the server API for TelemetryIngest service.
// All implementations must embed UnimplementedTelemetryIngestServer
// for forward compatibility.
type TelemetryIngestServer interface {
	Push(grpc.BidiStreamingServer[TelemetryBatch, Ack]) error
	mustEmbedUnimplementedTelemetryIngestServer()
}

// UnimplementedTelemetryIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryIngestServer struct{}

func (UnimplementedTelemetryIngestServer) Push(grpc.BidiStreamingServer[TelemetryBatch, Ack]) error {
	return status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedTelemetryIngestServer) mustEmbedUnimplementedTelemetryIngestServer() {}
func (UnimplementedTelemetryIngestServer) testEmbeddedByValue()                         {}

// UnsafeTelemetryIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryIngestServer will
// result in compilation errors.
type UnsafeTelemetryIngestServer interface {
	mustEmbedUnimplementedTelemetryIngestServer()
}

func RegisterTelemetryIngestServer(s grpc.ServiceRegistrar, srv TelemetryIngestServer) {
	// If the following call panics, it indicates UnimplementedTelemetryIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryIngest_ServiceDesc, srv)
}

func _TelemetryIngest_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetryIngestServer).Push(&grpc.GenericServerStream[TelemetryBatch, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryIngest_PushServer = grpc.BidiStreamingServer[TelemetryBatch, Ack]

// TelemetryIngest_ServiceDesc is the grpc.ServiceDesc for TelemetryIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.v1.TelemetryIngest",
	HandlerType: (*TelemetryIngestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _TelemetryIngest_Push_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "telemetry/v1/telemetry.proto",
}
