// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: probeipc/v1/probeipc.proto

package probeipcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Compression int32

const (
	Compression_COMPRESSION_NONE Compression = 0
	Compression_COMPRESSION_GZIP Compression = 1
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "COMPRESSION_NONE",
		1: "COMPRESSION_GZIP",
	}
	Compression_value = map[string]int32{
		"COMPRESSION_NONE": 0,
		"COMPRESSION_GZIP": 1,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_probeipc_v1_probeipc_proto_enumTypes[0].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_probeipc_v1_probeipc_proto_enumTypes[0]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_probeipc_v1_probeipc_proto_rawDescGZIP(), []int{0}
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_probeipc_v1_probeipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_probeipc_v1_probeipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_probeipc_v1_probeipc_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels        []*Label               `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_probeipc_v1_probeipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_probeipc_v1_probeipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_probeipc_v1_probeipc_proto_rawDescGZIP(), []int{1}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ProcessSample struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Pid                     int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name                    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CpuPercent              float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	RssBytes                uint64                 `protobuf:"varint,4,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	IoReadBps               float64                `protobuf:"fixed64,5,opt,name=io_read_bps,json=ioReadBps,proto3" json:"io_read_bps,omitempty"`
	IoWriteBps              float64                `protobuf:"fixed64,6,opt,name=io_write_bps,json=ioWriteBps,proto3" json:"io_write_bps,omitempty"`
	VoluntaryCtxSwitches    uint64                 `protobuf:"varint,7,opt,name=voluntary_ctx_switches,json=voluntaryCtxSwitches,proto3" json:"voluntary_ctx_switches,omitempty"`
	NonvoluntaryCtxSwitches uint64                 `protobuf:"varint,8,opt,name=nonvoluntary_ctx_switches,json=nonvoluntaryCtxSwitches,proto3" json:"nonvoluntary_ctx_switches,omitempty"`
	MinorFaults             uint64                 `protobuf:"varint,9,opt,name=minor_faults,json=minorFaults,proto3" json:"minor_faults,omitempty"`
	MajorFaults             uint64                 `protobuf:"varint,10,opt,name=major_faults,json=majorFaults,proto3" json:"major_faults,omitempty"`
	PssBytes                uint64                 `protobuf:"varint,11,opt,name=pss_bytes,json=pssBytes,proto3" json:"pss_bytes,omitempty"`
	NetTxQueueBytes         uint64                 `protobuf:"varint,12,opt,name=net_tx_queue_bytes,json=netTxQueueBytes,proto3" json:"net_tx_queue_bytes,omitempty"`
	NetRxQueueBytes         uint64                 `protobuf:"varint,13,opt,name=net_rx_queue_bytes,json=netRxQueueBytes,proto3" json:"net_rx_queue_bytes,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProcessSample) Reset() {
	*x = ProcessSample{}
	mi := &file_probeipc_v1_probeipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSample) ProtoMessage() {}

func (x *ProcessSample) ProtoReflect() protoreflect.Message {
	mi := &file_probeipc_v1_probeipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSample.ProtoReflect.Descriptor instead.
func (*ProcessSample) Descriptor() ([]byte, []int) {
	return file_probeipc_v1_probeipc_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessSample) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessSample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessSample) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessSample) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *ProcessSample) GetIoReadBps() float64 {
	if x != nil {
		return x.IoReadBps
	}
	return 0
}

func (x *ProcessSample) GetIoWriteBps() float64 {
	if x != nil {
		return x.IoWriteBps
	}
	return 0
}

func (x *ProcessSample) GetVoluntaryCtxSwitches() uint64 {
	if x != nil {
		return x.VoluntaryCtxSwitches
	}
	return 0
}

func (x *ProcessSample) GetNonvoluntaryCtxSwitches() uint64 {
	if x != nil {
		return x.NonvoluntaryCtxSwitches
	}
	return 0
}

func (x *ProcessSample) GetMinorFaults() uint64 {
	if x != nil {
		return x.MinorFaults
	}
	return 0
}

func (x *ProcessSample) GetMajorFaults() uint64 {
	if x != nil {
		return x.MajorFaults
	}
	return 0
}

func (x *ProcessSample) GetPssBytes() uint64 {
	if x != nil {
		return x.PssBytes
	}
	return 0
}

func (x *ProcessSample) GetNetTxQueueBytes() uint64 {
	if x != nil {
		return x.NetTxQueueBytes
	}
	return 0
}

func (x *ProcessSample) GetNetRxQueueBytes() uint64 {
	if x != nil {
		return x.NetRxQueueBytes
	}
	return 0
}

type ProbeBatch struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CollectedAtUnixNano    int64                  `protobuf:"varint,1,opt,name=collected_at_unix_nano,json=collectedAtUnixNano,proto3" json:"collected_at_unix_nano,omitempty"`
	MonotonicUnixNano      int64                  `protobuf:"varint,2,opt,name=monotonic_unix_nano,json=monotonicUnixNano,proto3" json:"monotonic_unix_nano,omitempty"`
	Metrics                []*Metric              `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Processes              []*ProcessSample       `protobuf:"bytes,4,rep,name=processes,proto3" json:"processes,omitempty"`
	WindowSamples          uint32                 `protobuf:"varint,5,opt,name=window_samples,json=windowSamples,proto3" json:"window_samples,omitempty"`
	Sequence               uint32                 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	DroppedDueBackpressure uint32                 `protobuf:"varint,7,opt,name=dropped_due_backpressure,json=droppedDueBackpressure,proto3" json:"dropped_due_backpressure,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProbeBatch) Reset() {
	*x = ProbeBatch{}
	mi := &file_probeipc_v1_probeipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeBatch) ProtoMessage() {}

func (x *ProbeBatch) ProtoReflect() protoreflect.Message {
	mi := &file_probeipc_v1_probeipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeBatch.ProtoReflect.Descriptor instead.
func (*ProbeBatch) Descriptor() ([]byte, []int) {
	return file_probeipc_v1_probeipc_proto_rawDescGZIP(), []int{3}
}

func (x *ProbeBatch) GetCollectedAtUnixNano() int64 {
	if x != nil {
		return x.CollectedAtUnixNano
	}
	return 0
}

func (x *ProbeBatch) GetMonotonicUnixNano() int64 {
	if x != nil {
		return x.MonotonicUnixNano
	}
	return 0
}

func (x *ProbeBatch) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ProbeBatch) GetProcesses() []*ProcessSample {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *ProbeBatch) GetWindowSamples() uint32 {
	if x != nil {
		return x.WindowSamples
	}
	return 0
}

func (x *ProbeBatch) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ProbeBatch) GetDroppedDueBackpressure() uint32 {
	if x != nil {
		return x.DroppedDueBackpressure
	}
	return 0
}

// FrameEnvelope is length-prefixed on the pipe/socket:
// [uint32 little-endian length][serialized FrameEnvelope]
// payload is serialized ProbeBatch, optionally compressed.
type FrameEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compression   Compression            `protobuf:"varint,1,opt,name=compression,proto3,enum=probeipc.v1.Compression" json:"compression,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadCrc32  uint32                 `protobuf:"varint,3,opt,name=payload_crc32,json=payloadCrc32,proto3" json:"payload_crc32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameEnvelope) Reset() {
	*x = FrameEnvelope{}
	mi := &file_probeipc_v1_probeipc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameEnvelope) ProtoMessage() {}

func (x *FrameEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_probeipc_v1_probeipc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameEnvelope.ProtoReflect.Descriptor instead.
func (*FrameEnvelope) Descriptor() ([]byte, []int) {
	return file_probeipc_v1_probeipc_proto_rawDescGZIP(), []int{4}
}

func (x *FrameEnvelope) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_COMPRESSION_NONE
}

func (x *FrameEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FrameEnvelope) GetPayloadCrc32() uint32 {
	if x != nil {
		return x.PayloadCrc32
	}
	return 0
}

var File_probeipc_v1_probeipc_proto protoreflect.FileDescriptor

const file_probeipc_v1_probeipc_proto_rawDesc = "" +
	"\n" +
	"\x1aprobeipc/v1/probeipc.proto\x12\vprobeipc.v1\"/\n" +
	"\x05Label\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"^\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12*\n" +
	"\x06labels\x18\x03 \x03(\v2\x12.probeipc.v1.LabelR\x06labels\"\xe4\x03\n" +
	"\rProcessSample\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\trss_bytes\x18\x04 \x01(\x04R\brssBytes\x12\x1e\n" +
	"\vio_read_bps\x18\x05 \x01(\x01R\tioReadBps\x12 \n" +
	"\fio_write_bps\x18\x06 \x01(\x01R\n" +
	"ioWriteBps\x124\n" +
	"\x16voluntary_ctx_switches\x18\a \x01(\x04R\x14voluntaryCtxSwitches\x12:\n" +
	"\x19nonvoluntary_ctx_switches\x18\b \x01(\x04R\x17nonvoluntaryCtxSwitches\x12!\n" +
	"\fminor_faults\x18\t \x01(\x04R\vminorFaults\x12!\n" +
	"\fmajor_faults\x18\n" +
	" \x01(\x04R\vmajorFaults\x12\x1b\n" +
	"\tpss_bytes\x18\v \x01(\x04R\bpssBytes\x12+\n" +
	"\x12net_tx_queue_bytes\x18\f \x01(\x04R\x0fnetTxQueueBytes\x12+\n" +
	"\x12net_rx_queue_bytes\x18\r \x01(\x04R\x0fnetRxQueueBytes\"\xd7\x02\n" +
	"\n" +
	"ProbeBatch\x123\n" +
	"\x16collected_at_unix_nano\x18\x01 \x01(\x03R\x13collectedAtUnixNano\x12.\n" +
	"\x13monotonic_unix_nano\x18\x02 \x01(\x03R\x11monotonicUnixNano\x12-\n" +
	"\ametrics\x18\x03 \x03(\v2\x13.probeipc.v1.MetricR\ametrics\x128\n" +
	"\tprocesses\x18\x04 \x03(\v2\x1a.probeipc.v1.ProcessSampleR\tprocesses\x12%\n" +
	"\x0ewindow_samples\x18\x05 \x01(\rR\rwindowSamples\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\rR\bsequence\x128\n" +
	"\x18dropped_due_backpressure\x18\a \x01(\rR\x16droppedDueBackpressure\"\x8a\x01\n" +
	"\rFrameEnvelope\x12:\n" +
	"\vcompression\x18\x01 \x01(\x0e2\x18.probeipc.v1.CompressionR\vcompression\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12#\n" +
	"\rpayload_crc32\x18\x03 \x01(\rR\fpayloadCrc32*9\n" +
	"\vCompression\x12\x14\n" +
	"\x10COMPRESSION_NONE\x10\x00\x12\x14\n" +
	"\x10COMPRESSION_GZIP\x10\x01BBZ@github.com/jfang2048/ai_sre_agent_pub/pkg/probeipc/v1;probeipcv1b\x06proto3"

var (
	file_probeipc_v1_probeipc_proto_rawDescOnce sync.Once
	file_probeipc_v1_probeipc_proto_rawDescData []byte
)

func file_probeipc_v1_probeipc_proto_rawDescGZIP() []byte {
	file_probeipc_v1_probeipc_proto_rawDescOnce.Do(func() {
		file_probeipc_v1_probeipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_probeipc_v1_probeipc_proto_rawDesc), len(file_probeipc_v1_probeipc_proto_rawDesc)))
	})
	return file_probeipc_v1_probeipc_proto_rawDescData
}

var file_probeipc_v1_probeipc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_probeipc_v1_probeipc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_probeipc_v1_probeipc_proto_goTypes = []any{
	(Compression)(0),      // 0: probeipc.v1.Compression
	(*Label)(nil),         // 1: probeipc.v1.Label
	(*Metric)(nil),        // 2: probeipc.v1.Metric
	(*ProcessSample)(nil), // 3: probeipc.v1.ProcessSample
	(*ProbeBatch)(nil),    // 4: probeipc.v1.ProbeBatch
	(*FrameEnvelope)(nil), // 5: probeipc.v1.FrameEnvelope
}
var file_probeipc_v1_probeipc_proto_depIdxs = []int32{
	1, // 0: probeipc.v1.Metric.labels:type_name -> probeipc.v1.Label
	2, // 1: probeipc.v1.ProbeBatch.metrics:type_name -> probeipc.v1.Metric
	3, // 2: probeipc.v1.ProbeBatch.processes:type_name -> probeipc.v1.ProcessSample
	0, // 3: probeipc.v1.FrameEnvelope.compression:type_name -> probeipc.v1.Compression
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_probeipc_v1_probeipc_proto_init() }
func file_probeipc_v1_probeipc_proto_init() {
	if File_probeipc_v1_probeipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_probeipc_v1_probeipc_proto_rawDesc), len(file_probeipc_v1_probeipc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_probeipc_v1_probeipc_proto_goTypes,
		DependencyIndexes: file_probeipc_v1_probeipc_proto_depIdxs,
		EnumInfos:         file_probeipc_v1_probeipc_proto_enumTypes,
		MessageInfos:      file_probeipc_v1_probeipc_proto_msgTypes,
	}.Build()
	File_probeipc_v1_probeipc_proto = out.File
	file_probeipc_v1_probeipc_proto_goTypes = nil
	file_probeipc_v1_probeipc_proto_depIdxs = nil
}
