// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: action.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActionExecutionService_ExecuteAction_FullMethodName  = "/api.proto.ActionExecutionService/ExecuteAction"
	ActionExecutionService_ExecuteBatch_FullMethodName   = "/api.proto.ActionExecutionService/ExecuteBatch"
	ActionExecutionService_ExecutePlan_FullMethodName    = "/api.proto.ActionExecutionService/ExecutePlan"
	ActionExecutionService_GetAction_FullMethodName      = "/api.proto.ActionExecutionService/GetAction"
	ActionExecutionService_ListActions_FullMethodName    = "/api.proto.ActionExecutionService/ListActions"
	ActionExecutionService_CancelAction_FullMethodName   = "/api.proto.ActionExecutionService/CancelAction"
	ActionExecutionService_RollbackAction_FullMethodName = "/api.proto.ActionExecutionService/RollbackAction"
)

// ActionExecutionServiceClient is the client API for ActionExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ActionExecutionService handles action execution
type ActionExecutionServiceClient interface {
	// Execute a single action
	ExecuteAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Execute a batch of actions
	ExecuteBatch(ctx context.Context, in *ActionBatch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionResponse], error)
	// Execute an action plan
	ExecutePlan(ctx context.Context, in *ActionPlan, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionResponse], error)
	// Get action status
	GetAction(ctx context.Context, in *GetActionRequest, opts ...grpc.CallOption) (*Action, error)
	// List actions with filters
	ListActions(ctx context.Context, in *ListActionsRequest, opts ...grpc.CallOption) (*ListActionsResponse, error)
	// Cancel a pending or executing action
	CancelAction(ctx context.Context, in *CancelActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Rollback a completed action
	RollbackAction(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*ActionResponse, error)
}

type actionExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActionExecutionServiceClient(cc grpc.ClientConnInterface) ActionExecutionServiceClient {
	return &actionExecutionServiceClient{cc}
}

func (c *actionExecutionServiceClient) ExecuteAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ActionExecutionService_ExecuteAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionExecutionServiceClient) ExecuteBatch(ctx context.Context, in *ActionBatch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ActionExecutionService_ServiceDesc.Streams[0], ActionExecutionService_ExecuteBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActionBatch, ActionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActionExecutionService_ExecuteBatchClient = grpc.ServerStreamingClient[ActionResponse]

func (c *actionExecutionServiceClient) ExecutePlan(ctx context.Context, in *ActionPlan, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ActionExecutionService_ServiceDesc.Streams[1], ActionExecutionService_ExecutePlan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActionPlan, ActionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActionExecutionService_ExecutePlanClient = grpc.ServerStreamingClient[ActionResponse]

func (c *actionExecutionServiceClient) GetAction(ctx context.Context, in *GetActionRequest, opts ...grpc.CallOption) (*Action, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Action)
	err := c.cc.Invoke(ctx, ActionExecutionService_GetAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionExecutionServiceClient) ListActions(ctx context.Context, in *ListActionsRequest, opts ...grpc.CallOption) (*ListActionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActionsResponse)
	err := c.cc.Invoke(ctx, ActionExecutionService_ListActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionExecutionServiceClient) CancelAction(ctx context.Context, in *CancelActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ActionExecutionService_CancelAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionExecutionServiceClient) RollbackAction(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ActionExecutionService_RollbackAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActionExecutionServiceServer is the server API for ActionExecutionService service.
// All implementations must embed UnimplementedActionExecutionServiceServer
// for forward compatibility.
//
// ActionExecutionService handles action execution
type ActionExecutionServiceServer interface {
	// Execute a single action
	ExecuteAction(context.Context, *ActionRequest) (*ActionResponse, error)
	// Execute a batch of actions
	ExecuteBatch(*ActionBatch, grpc.ServerStreamingServer[ActionResponse]) error
	// Execute an action plan
	ExecutePlan(*ActionPlan, grpc.ServerStreamingServer[ActionResponse]) error
	// Get action status
	GetAction(context.Context, *GetActionRequest) (*Action, error)
	// List actions with filters
	ListActions(context.Context, *ListActionsRequest) (*ListActionsResponse, error)
	// Cancel a pending or executing action
	CancelAction(context.Context, *CancelActionRequest) (*ActionResponse, error)
	// Rollback a completed action
	RollbackAction(context.Context, *RollbackRequest) (*ActionResponse, error)
	mustEmbedUnimplementedActionExecutionServiceServer()
}

// UnimplementedActionExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActionExecutionServiceServer struct{}

func (UnimplementedActionExecutionServiceServer) ExecuteAction(context.Context, *ActionRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteAction not implemented")
}
func (UnimplementedActionExecutionServiceServer) ExecuteBatch(*ActionBatch, grpc.ServerStreamingServer[ActionResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteBatch not implemented")
}
func (UnimplementedActionExecutionServiceServer) ExecutePlan(*ActionPlan, grpc.ServerStreamingServer[ActionResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecutePlan not implemented")
}
func (UnimplementedActionExecutionServiceServer) GetAction(context.Context, *GetActionRequest) (*Action, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAction not implemented")
}
func (UnimplementedActionExecutionServiceServer) ListActions(context.Context, *ListActionsRequest) (*ListActionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActions not implemented")
}
func (UnimplementedActionExecutionServiceServer) CancelAction(context.Context, *CancelActionRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelAction not implemented")
}
func (UnimplementedActionExecutionServiceServer) RollbackAction(context.Context, *RollbackRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackAction not implemented")
}
func (UnimplementedActionExecutionServiceServer) mustEmbedUnimplementedActionExecutionServiceServer() {
}
func (UnimplementedActionExecutionServiceServer) testEmbeddedByValue() {}

// UnsafeActionExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActionExecutionServiceServer will
// result in compilation errors.
type UnsafeActionExecutionServiceServer interface {
	mustEmbedUnimplementedActionExecutionServiceServer()
}

func RegisterActionExecutionServiceServer(s grpc.ServiceRegistrar, srv ActionExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedActionExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActionExecutionService_ServiceDesc, srv)
}

func _ActionExecutionService_ExecuteAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionExecutionServiceServer).ExecuteAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionExecutionService_ExecuteAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionExecutionServiceServer).ExecuteAction(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionExecutionService_ExecuteBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActionBatch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ActionExecutionServiceServer).ExecuteBatch(m, &grpc.GenericServerStream[ActionBatch, ActionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActionExecutionService_ExecuteBatchServer = grpc.ServerStreamingServer[ActionResponse]

func _ActionExecutionService_ExecutePlan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActionPlan)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ActionExecutionServiceServer).ExecutePlan(m, &grpc.GenericServerStream[ActionPlan, ActionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActionExecutionService_ExecutePlanServer = grpc.ServerStreamingServer[ActionResponse]

func _ActionExecutionService_GetAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionExecutionServiceServer).GetAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionExecutionService_GetAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionExecutionServiceServer).GetAction(ctx, req.(*GetActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionExecutionService_ListActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionExecutionServiceServer).ListActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionExecutionService_ListActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionExecutionServiceServer).ListActions(ctx, req.(*ListActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionExecutionService_CancelAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionExecutionServiceServer).CancelAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionExecutionService_CancelAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionExecutionServiceServer).CancelAction(ctx, req.(*CancelActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionExecutionService_RollbackAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionExecutionServiceServer).RollbackAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionExecutionService_RollbackAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionExecutionServiceServer).RollbackAction(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActionExecutionService_ServiceDesc is the grpc.ServiceDesc for ActionExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActionExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.ActionExecutionService",
	HandlerType: (*ActionExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteAction",
			Handler:    _ActionExecutionService_ExecuteAction_Handler,
		},
		{
			MethodName: "GetAction",
			Handler:    _ActionExecutionService_GetAction_Handler,
		},
		{
			MethodName: "ListActions",
			Handler:    _ActionExecutionService_ListActions_Handler,
		},
		{
			MethodName: "CancelAction",
			Handler:    _ActionExecutionService_CancelAction_Handler,
		},
		{
			MethodName: "RollbackAction",
			Handler:    _ActionExecutionService_RollbackAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteBatch",
			Handler:       _ActionExecutionService_ExecuteBatch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecutePlan",
			Handler:       _ActionExecutionService_ExecutePlan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "action.proto",
}
