// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: action.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActionCategory groups actions by type
type ActionCategory int32

const (
	ActionCategory_ACTION_CATEGORY_UNKNOWN        ActionCategory = 0
	ActionCategory_ACTION_CATEGORY_SCALING        ActionCategory = 1  // Horizontal/vertical scaling
	ActionCategory_ACTION_CATEGORY_RESTART        ActionCategory = 2  // Service/pod restart
	ActionCategory_ACTION_CATEGORY_FAILOVER       ActionCategory = 3  // Traffic failover
	ActionCategory_ACTION_CATEGORY_ROLLBACK       ActionCategory = 4  // Version rollback
	ActionCategory_ACTION_CATEGORY_CONFIG_CHANGE  ActionCategory = 5  // Configuration update
	ActionCategory_ACTION_CATEGORY_RESOURCE_LIMIT ActionCategory = 6  // CPU/memory limit changes
	ActionCategory_ACTION_CATEGORY_NETWORK        ActionCategory = 7  // Firewall, routing changes
	ActionCategory_ACTION_CATEGORY_STORAGE        ActionCategory = 8  // Snapshot, volume operations
	ActionCategory_ACTION_CATEGORY_CUSTOM         ActionCategory = 99 // Custom/scripted actions
)

// Enum value maps for ActionCategory.
var (
	ActionCategory_name = map[int32]string{
		0:  "ACTION_CATEGORY_UNKNOWN",
		1:  "ACTION_CATEGORY_SCALING",
		2:  "ACTION_CATEGORY_RESTART",
		3:  "ACTION_CATEGORY_FAILOVER",
		4:  "ACTION_CATEGORY_ROLLBACK",
		5:  "ACTION_CATEGORY_CONFIG_CHANGE",
		6:  "ACTION_CATEGORY_RESOURCE_LIMIT",
		7:  "ACTION_CATEGORY_NETWORK",
		8:  "ACTION_CATEGORY_STORAGE",
		99: "ACTION_CATEGORY_CUSTOM",
	}
	ActionCategory_value = map[string]int32{
		"ACTION_CATEGORY_UNKNOWN":        0,
		"ACTION_CATEGORY_SCALING":        1,
		"ACTION_CATEGORY_RESTART":        2,
		"ACTION_CATEGORY_FAILOVER":       3,
		"ACTION_CATEGORY_ROLLBACK":       4,
		"ACTION_CATEGORY_CONFIG_CHANGE":  5,
		"ACTION_CATEGORY_RESOURCE_LIMIT": 6,
		"ACTION_CATEGORY_NETWORK":        7,
		"ACTION_CATEGORY_STORAGE":        8,
		"ACTION_CATEGORY_CUSTOM":         99,
	}
)

func (x ActionCategory) Enum() *ActionCategory {
	p := new(ActionCategory)
	*p = x
	return p
}

func (x ActionCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[0].Descriptor()
}

func (ActionCategory) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[0]
}

func (x ActionCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionCategory.Descriptor instead.
func (ActionCategory) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{0}
}

// ActionState represents the lifecycle state of an action
type ActionState int32

const (
	ActionState_ACTION_STATE_PENDING     ActionState = 0 // Awaiting execution
	ActionState_ACTION_STATE_VALIDATING  ActionState = 1 // Safety checks in progress
	ActionState_ACTION_STATE_APPROVED    ActionState = 2 // Approved for execution
	ActionState_ACTION_STATE_REJECTED    ActionState = 3 // Rejected by validator
	ActionState_ACTION_STATE_EXECUTING   ActionState = 4 // Currently executing
	ActionState_ACTION_STATE_COMPLETED   ActionState = 5 // Finished successfully
	ActionState_ACTION_STATE_FAILED      ActionState = 6 // Failed with error
	ActionState_ACTION_STATE_ROLLED_BACK ActionState = 7 // Executed but rolled back
	ActionState_ACTION_STATE_CANCELLED   ActionState = 8 // Cancelled before execution
)

// Enum value maps for ActionState.
var (
	ActionState_name = map[int32]string{
		0: "ACTION_STATE_PENDING",
		1: "ACTION_STATE_VALIDATING",
		2: "ACTION_STATE_APPROVED",
		3: "ACTION_STATE_REJECTED",
		4: "ACTION_STATE_EXECUTING",
		5: "ACTION_STATE_COMPLETED",
		6: "ACTION_STATE_FAILED",
		7: "ACTION_STATE_ROLLED_BACK",
		8: "ACTION_STATE_CANCELLED",
	}
	ActionState_value = map[string]int32{
		"ACTION_STATE_PENDING":     0,
		"ACTION_STATE_VALIDATING":  1,
		"ACTION_STATE_APPROVED":    2,
		"ACTION_STATE_REJECTED":    3,
		"ACTION_STATE_EXECUTING":   4,
		"ACTION_STATE_COMPLETED":   5,
		"ACTION_STATE_FAILED":      6,
		"ACTION_STATE_ROLLED_BACK": 7,
		"ACTION_STATE_CANCELLED":   8,
	}
)

func (x ActionState) Enum() *ActionState {
	p := new(ActionState)
	*p = x
	return p
}

func (x ActionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionState) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[1].Descriptor()
}

func (ActionState) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[1]
}

func (x ActionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionState.Descriptor instead.
func (ActionState) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1}
}

// PlanStatus indicates the status of an action plan
type PlanStatus int32

const (
	PlanStatus_PLAN_STATUS_PENDING             PlanStatus = 0
	PlanStatus_PLAN_STATUS_IN_PROGRESS         PlanStatus = 1
	PlanStatus_PLAN_STATUS_COMPLETED           PlanStatus = 2
	PlanStatus_PLAN_STATUS_FAILED              PlanStatus = 3
	PlanStatus_PLAN_STATUS_PARTIALLY_COMPLETED PlanStatus = 4
	PlanStatus_PLAN_STATUS_CANCELLED           PlanStatus = 5
)

// Enum value maps for PlanStatus.
var (
	PlanStatus_name = map[int32]string{
		0: "PLAN_STATUS_PENDING",
		1: "PLAN_STATUS_IN_PROGRESS",
		2: "PLAN_STATUS_COMPLETED",
		3: "PLAN_STATUS_FAILED",
		4: "PLAN_STATUS_PARTIALLY_COMPLETED",
		5: "PLAN_STATUS_CANCELLED",
	}
	PlanStatus_value = map[string]int32{
		"PLAN_STATUS_PENDING":             0,
		"PLAN_STATUS_IN_PROGRESS":         1,
		"PLAN_STATUS_COMPLETED":           2,
		"PLAN_STATUS_FAILED":              3,
		"PLAN_STATUS_PARTIALLY_COMPLETED": 4,
		"PLAN_STATUS_CANCELLED":           5,
	}
)

func (x PlanStatus) Enum() *PlanStatus {
	p := new(PlanStatus)
	*p = x
	return p
}

func (x PlanStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlanStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[2].Descriptor()
}

func (PlanStatus) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[2]
}

func (x PlanStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlanStatus.Descriptor instead.
func (PlanStatus) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{2}
}

// Action represents a remediation action that can be executed
type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      ActionCategory         `protobuf:"varint,4,opt,name=category,proto3,enum=api.proto.ActionCategory" json:"category,omitempty"`
	Parameters    *ActionParameters      `protobuf:"bytes,5,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Constraints   *ActionConstraints     `protobuf:"bytes,6,opt,name=constraints,proto3" json:"constraints,omitempty"`
	State         ActionState            `protobuf:"varint,7,opt,name=state,proto3,enum=api.proto.ActionState" json:"state,omitempty"`
	Result        *ActionResult          `protobuf:"bytes,8,opt,name=result,proto3" json:"result,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	StartedAt     int64                  `protobuf:"varint,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // Agent ID or human operator
	Reason        string                 `protobuf:"bytes,13,opt,name=reason,proto3" json:"reason,omitempty"`                        // Why this action was taken
	Tags          []string               `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Action) GetCategory() ActionCategory {
	if x != nil {
		return x.Category
	}
	return ActionCategory_ACTION_CATEGORY_UNKNOWN
}

func (x *Action) GetParameters() *ActionParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Action) GetConstraints() *ActionConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *Action) GetState() ActionState {
	if x != nil {
		return x.State
	}
	return ActionState_ACTION_STATE_PENDING
}

func (x *Action) GetResult() *ActionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Action) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Action) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Action) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *Action) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Action) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Action) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ActionResult contains the outcome of an executed action
type ActionResult struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode    string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// Changes made
	Changes []*ChangeSummary `protobuf:"bytes,4,rep,name=changes,proto3" json:"changes,omitempty"`
	// Verification results
	Verification *VerificationResult `protobuf:"bytes,5,opt,name=verification,proto3" json:"verification,omitempty"`
	// Rollback information
	Rollback      *RollbackInfo `protobuf:"bytes,6,opt,name=rollback,proto3" json:"rollback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1}
}

func (x *ActionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ActionResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ActionResult) GetChanges() []*ChangeSummary {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ActionResult) GetVerification() *VerificationResult {
	if x != nil {
		return x.Verification
	}
	return nil
}

func (x *ActionResult) GetRollback() *RollbackInfo {
	if x != nil {
		return x.Rollback
	}
	return nil
}

// ChangeSummary describes a single change made by an action
type ChangeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // e.g., "Deployment", "ConfigMap"
	ResourceName  string                 `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ChangeType    string                 `protobuf:"bytes,4,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"` // "created", "updated", "deleted", "scaled"
	Field         string                 `protobuf:"bytes,5,opt,name=field,proto3" json:"field,omitempty"`                             // Field that was changed
	OldValue      string                 `protobuf:"bytes,6,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue      string                 `protobuf:"bytes,7,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSummary) Reset() {
	*x = ChangeSummary{}
	mi := &file_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSummary) ProtoMessage() {}

func (x *ChangeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSummary.ProtoReflect.Descriptor instead.
func (*ChangeSummary) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeSummary) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ChangeSummary) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ChangeSummary) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ChangeSummary) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *ChangeSummary) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ChangeSummary) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

func (x *ChangeSummary) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

// VerificationResult contains post-action verification data
type VerificationResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Verified           bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	VerificationMethod string                 `protobuf:"bytes,2,opt,name=verification_method,json=verificationMethod,proto3" json:"verification_method,omitempty"`
	MetricChecks       []*MetricCheck         `protobuf:"bytes,3,rep,name=metric_checks,json=metricChecks,proto3" json:"metric_checks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VerificationResult) Reset() {
	*x = VerificationResult{}
	mi := &file_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResult) ProtoMessage() {}

func (x *VerificationResult) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResult.ProtoReflect.Descriptor instead.
func (*VerificationResult) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationResult) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerificationResult) GetVerificationMethod() string {
	if x != nil {
		return x.VerificationMethod
	}
	return ""
}

func (x *VerificationResult) GetMetricChecks() []*MetricCheck {
	if x != nil {
		return x.MetricChecks
	}
	return nil
}

// MetricCheck verifies a specific metric after action
type MetricCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Threshold     float64                `protobuf:"fixed64,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	ActualValue   float64                `protobuf:"fixed64,3,opt,name=actual_value,json=actualValue,proto3" json:"actual_value,omitempty"`
	Passed        bool                   `protobuf:"varint,4,opt,name=passed,proto3" json:"passed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricCheck) Reset() {
	*x = MetricCheck{}
	mi := &file_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricCheck) ProtoMessage() {}

func (x *MetricCheck) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricCheck.ProtoReflect.Descriptor instead.
func (*MetricCheck) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{4}
}

func (x *MetricCheck) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *MetricCheck) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *MetricCheck) GetActualValue() float64 {
	if x != nil {
		return x.ActualValue
	}
	return 0
}

func (x *MetricCheck) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

// RollbackInfo contains information for rolling back an action
type RollbackInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CanRollback    bool                   `protobuf:"varint,1,opt,name=can_rollback,json=canRollback,proto3" json:"can_rollback,omitempty"`
	RollbackMethod string                 `protobuf:"bytes,2,opt,name=rollback_method,json=rollbackMethod,proto3" json:"rollback_method,omitempty"`
	RollbackState  map[string]string      `protobuf:"bytes,3,rep,name=rollback_state,json=rollbackState,proto3" json:"rollback_state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // State needed for rollback
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RollbackInfo) Reset() {
	*x = RollbackInfo{}
	mi := &file_action_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackInfo) ProtoMessage() {}

func (x *RollbackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackInfo.ProtoReflect.Descriptor instead.
func (*RollbackInfo) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{5}
}

func (x *RollbackInfo) GetCanRollback() bool {
	if x != nil {
		return x.CanRollback
	}
	return false
}

func (x *RollbackInfo) GetRollbackMethod() string {
	if x != nil {
		return x.RollbackMethod
	}
	return ""
}

func (x *RollbackInfo) GetRollbackState() map[string]string {
	if x != nil {
		return x.RollbackState
	}
	return nil
}

// ActionParameters contains execution parameters
type ActionParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target specification
	TargetType string `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // "deployment", "pod", "service", etc.
	TargetName string `protobuf:"bytes,2,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	Namespace  string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Action-specific parameters
	StringParams map[string]string  `protobuf:"bytes,4,rep,name=string_params,json=stringParams,proto3" json:"string_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IntParams    map[string]int64   `protobuf:"bytes,5,rep,name=int_params,json=intParams,proto3" json:"int_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FloatParams  map[string]float64 `protobuf:"bytes,6,rep,name=float_params,json=floatParams,proto3" json:"float_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	BoolParams   map[string]bool    `protobuf:"bytes,7,rep,name=bool_params,json=boolParams,proto3" json:"bool_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// For scaling actions
	Replicas int32           `protobuf:"varint,10,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Resource *ResourceAmount `protobuf:"bytes,11,opt,name=resource,proto3" json:"resource,omitempty"`
	// For config changes
	ConfigUpdates map[string]string `protobuf:"bytes,12,rep,name=config_updates,json=configUpdates,proto3" json:"config_updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionParameters) Reset() {
	*x = ActionParameters{}
	mi := &file_action_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionParameters) ProtoMessage() {}

func (x *ActionParameters) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionParameters.ProtoReflect.Descriptor instead.
func (*ActionParameters) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{6}
}

func (x *ActionParameters) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ActionParameters) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *ActionParameters) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ActionParameters) GetStringParams() map[string]string {
	if x != nil {
		return x.StringParams
	}
	return nil
}

func (x *ActionParameters) GetIntParams() map[string]int64 {
	if x != nil {
		return x.IntParams
	}
	return nil
}

func (x *ActionParameters) GetFloatParams() map[string]float64 {
	if x != nil {
		return x.FloatParams
	}
	return nil
}

func (x *ActionParameters) GetBoolParams() map[string]bool {
	if x != nil {
		return x.BoolParams
	}
	return nil
}

func (x *ActionParameters) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *ActionParameters) GetResource() *ResourceAmount {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ActionParameters) GetConfigUpdates() map[string]string {
	if x != nil {
		return x.ConfigUpdates
	}
	return nil
}

// ResourceAmount represents CPU/memory amounts
type ResourceAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`       // e.g., "500m", "2"
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"` // e.g., "512Mi", "2Gi"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceAmount) Reset() {
	*x = ResourceAmount{}
	mi := &file_action_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAmount) ProtoMessage() {}

func (x *ResourceAmount) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAmount.ProtoReflect.Descriptor instead.
func (*ResourceAmount) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceAmount) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourceAmount) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

// ActionConstraints limits when/how an action can execute
type ActionConstraints struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time windows
	AllowedAfter  int64 `protobuf:"varint,1,opt,name=allowed_after,json=allowedAfter,proto3" json:"allowed_after,omitempty"`    // Unix timestamp - don't execute before
	AllowedBefore int64 `protobuf:"varint,2,opt,name=allowed_before,json=allowedBefore,proto3" json:"allowed_before,omitempty"` // Unix timestamp - don't execute after
	// Approval requirements
	RequiresApproval bool     `protobuf:"varint,3,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	Approvers        []string `protobuf:"bytes,4,rep,name=approvers,proto3" json:"approvers,omitempty"`
	// Safety limits
	MaxReplicas  int32           `protobuf:"varint,5,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas,omitempty"`
	MinReplicas  int32           `protobuf:"varint,6,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	MaxResources *ResourceAmount `protobuf:"bytes,7,opt,name=max_resources,json=maxResources,proto3" json:"max_resources,omitempty"`
	// Conditions
	RequiredConditions []string `protobuf:"bytes,8,rep,name=required_conditions,json=requiredConditions,proto3" json:"required_conditions,omitempty"` // All must be true
	BlockingConditions []string `protobuf:"bytes,9,rep,name=blocking_conditions,json=blockingConditions,proto3" json:"blocking_conditions,omitempty"` // None can be true
	// Rate limiting
	MaxExecutionsPerHour int32 `protobuf:"varint,10,opt,name=max_executions_per_hour,json=maxExecutionsPerHour,proto3" json:"max_executions_per_hour,omitempty"`
	CooldownSeconds      int32 `protobuf:"varint,11,opt,name=cooldown_seconds,json=cooldownSeconds,proto3" json:"cooldown_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ActionConstraints) Reset() {
	*x = ActionConstraints{}
	mi := &file_action_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionConstraints) ProtoMessage() {}

func (x *ActionConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionConstraints.ProtoReflect.Descriptor instead.
func (*ActionConstraints) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{8}
}

func (x *ActionConstraints) GetAllowedAfter() int64 {
	if x != nil {
		return x.AllowedAfter
	}
	return 0
}

func (x *ActionConstraints) GetAllowedBefore() int64 {
	if x != nil {
		return x.AllowedBefore
	}
	return 0
}

func (x *ActionConstraints) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *ActionConstraints) GetApprovers() []string {
	if x != nil {
		return x.Approvers
	}
	return nil
}

func (x *ActionConstraints) GetMaxReplicas() int32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

func (x *ActionConstraints) GetMinReplicas() int32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *ActionConstraints) GetMaxResources() *ResourceAmount {
	if x != nil {
		return x.MaxResources
	}
	return nil
}

func (x *ActionConstraints) GetRequiredConditions() []string {
	if x != nil {
		return x.RequiredConditions
	}
	return nil
}

func (x *ActionConstraints) GetBlockingConditions() []string {
	if x != nil {
		return x.BlockingConditions
	}
	return nil
}

func (x *ActionConstraints) GetMaxExecutionsPerHour() int32 {
	if x != nil {
		return x.MaxExecutionsPerHour
	}
	return 0
}

func (x *ActionConstraints) GetCooldownSeconds() int32 {
	if x != nil {
		return x.CooldownSeconds
	}
	return 0
}

// ActionRequest is a request to execute an action
type ActionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Action         *Action                `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	DryRun         bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"` // Validate but don't execute
	TimeoutSeconds int64                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // For tracking related actions
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_action_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{9}
}

func (x *ActionRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ActionRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *ActionRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ActionRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// ActionResponse is the response to an action request
type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ActionId      string                 `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	State         ActionState            `protobuf:"varint,4,opt,name=state,proto3,enum=api.proto.ActionState" json:"state,omitempty"`
	Warnings      []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_action_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{10}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActionResponse) GetState() ActionState {
	if x != nil {
		return x.State
	}
	return ActionState_ACTION_STATE_PENDING
}

func (x *ActionResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// ActionBatch groups multiple actions for atomic execution
type ActionBatch struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Actions          []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	ExecuteAllOrNone bool                   `protobuf:"varint,2,opt,name=execute_all_or_none,json=executeAllOrNone,proto3" json:"execute_all_or_none,omitempty"` // Stop on first failure
	TimeoutSeconds   int64                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActionBatch) Reset() {
	*x = ActionBatch{}
	mi := &file_action_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionBatch) ProtoMessage() {}

func (x *ActionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionBatch.ProtoReflect.Descriptor instead.
func (*ActionBatch) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{11}
}

func (x *ActionBatch) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ActionBatch) GetExecuteAllOrNone() bool {
	if x != nil {
		return x.ExecuteAllOrNone
	}
	return false
}

func (x *ActionBatch) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// ActionPlan represents a sequence of actions to achieve a goal
type ActionPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Goal          string                 `protobuf:"bytes,4,opt,name=goal,proto3" json:"goal,omitempty"` // What this plan aims to achieve
	Steps         []*ActionStep          `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	Status        PlanStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=api.proto.PlanStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionPlan) Reset() {
	*x = ActionPlan{}
	mi := &file_action_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionPlan) ProtoMessage() {}

func (x *ActionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionPlan.ProtoReflect.Descriptor instead.
func (*ActionPlan) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{12}
}

func (x *ActionPlan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionPlan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionPlan) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *ActionPlan) GetSteps() []*ActionStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ActionPlan) GetStatus() PlanStatus {
	if x != nil {
		return x.Status
	}
	return PlanStatus_PLAN_STATUS_PENDING
}

func (x *ActionPlan) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ActionPlan) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// ActionStep is a single step in an action plan
type ActionStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Order         int32                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Action        *Action                `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	DependsOn     []string               `protobuf:"bytes,4,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"` // IDs of steps that must complete first
	Optional      bool                   `protobuf:"varint,5,opt,name=optional,proto3" json:"optional,omitempty"`                   // If true, plan continues even if this step fails
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionStep) Reset() {
	*x = ActionStep{}
	mi := &file_action_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionStep) ProtoMessage() {}

func (x *ActionStep) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionStep.ProtoReflect.Descriptor instead.
func (*ActionStep) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{13}
}

func (x *ActionStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionStep) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *ActionStep) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ActionStep) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *ActionStep) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

// GetActionRequest
type GetActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionRequest) Reset() {
	*x = GetActionRequest{}
	mi := &file_action_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionRequest) ProtoMessage() {}

func (x *GetActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionRequest.ProtoReflect.Descriptor instead.
func (*GetActionRequest) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{14}
}

func (x *GetActionRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

// ListActionsRequest
type ListActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Category      ActionCategory         `protobuf:"varint,3,opt,name=category,proto3,enum=api.proto.ActionCategory" json:"category,omitempty"`
	State         ActionState            `protobuf:"varint,4,opt,name=state,proto3,enum=api.proto.ActionState" json:"state,omitempty"`
	CreatedAfter  int64                  `protobuf:"varint,5,opt,name=created_after,json=createdAfter,proto3" json:"created_after,omitempty"`
	CreatedBefore int64                  `protobuf:"varint,6,opt,name=created_before,json=createdBefore,proto3" json:"created_before,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionsRequest) Reset() {
	*x = ListActionsRequest{}
	mi := &file_action_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionsRequest) ProtoMessage() {}

func (x *ListActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionsRequest.ProtoReflect.Descriptor instead.
func (*ListActionsRequest) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{15}
}

func (x *ListActionsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListActionsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListActionsRequest) GetCategory() ActionCategory {
	if x != nil {
		return x.Category
	}
	return ActionCategory_ACTION_CATEGORY_UNKNOWN
}

func (x *ListActionsRequest) GetState() ActionState {
	if x != nil {
		return x.State
	}
	return ActionState_ACTION_STATE_PENDING
}

func (x *ListActionsRequest) GetCreatedAfter() int64 {
	if x != nil {
		return x.CreatedAfter
	}
	return 0
}

func (x *ListActionsRequest) GetCreatedBefore() int64 {
	if x != nil {
		return x.CreatedBefore
	}
	return 0
}

func (x *ListActionsRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

// ListActionsResponse
type ListActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionsResponse) Reset() {
	*x = ListActionsResponse{}
	mi := &file_action_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionsResponse) ProtoMessage() {}

func (x *ListActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionsResponse.ProtoReflect.Descriptor instead.
func (*ListActionsResponse) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{16}
}

func (x *ListActionsResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ListActionsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// CancelActionRequest
type CancelActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelActionRequest) Reset() {
	*x = CancelActionRequest{}
	mi := &file_action_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelActionRequest) ProtoMessage() {}

func (x *CancelActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelActionRequest.ProtoReflect.Descriptor instead.
func (*CancelActionRequest) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{17}
}

func (x *CancelActionRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *CancelActionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RollbackRequest
type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"` // Skip confirmation if action is old
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_action_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{18}
}

func (x *RollbackRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *RollbackRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RollbackRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

var File_action_proto protoreflect.FileDescriptor

const file_action_proto_rawDesc = "" +
	"\n" +
	"\faction.proto\x12\tapi.proto\"\x8d\x04\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x19.api.proto.ActionCategoryR\bcategory\x12;\n" +
	"\n" +
	"parameters\x18\x05 \x01(\v2\x1b.api.proto.ActionParametersR\n" +
	"parameters\x12>\n" +
	"\vconstraints\x18\x06 \x01(\v2\x1c.api.proto.ActionConstraintsR\vconstraints\x12,\n" +
	"\x05state\x18\a \x01(\x0e2\x16.api.proto.ActionStateR\x05state\x12/\n" +
	"\x06result\x18\b \x01(\v2\x17.api.proto.ActionResultR\x06result\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\v \x01(\x03R\vcompletedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\f \x01(\tR\tcreatedBy\x12\x16\n" +
	"\x06reason\x18\r \x01(\tR\x06reason\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\"\x98\x02\n" +
	"\fActionResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x122\n" +
	"\achanges\x18\x04 \x03(\v2\x18.api.proto.ChangeSummaryR\achanges\x12A\n" +
	"\fverification\x18\x05 \x01(\v2\x1d.api.proto.VerificationResultR\fverification\x123\n" +
	"\brollback\x18\x06 \x01(\v2\x17.api.proto.RollbackInfoR\brollback\"\xe8\x01\n" +
	"\rChangeSummary\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12#\n" +
	"\rresource_name\x18\x02 \x01(\tR\fresourceName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vchange_type\x18\x04 \x01(\tR\n" +
	"changeType\x12\x14\n" +
	"\x05field\x18\x05 \x01(\tR\x05field\x12\x1b\n" +
	"\told_value\x18\x06 \x01(\tR\boldValue\x12\x1b\n" +
	"\tnew_value\x18\a \x01(\tR\bnewValue\"\x9e\x01\n" +
	"\x12VerificationResult\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12/\n" +
	"\x13verification_method\x18\x02 \x01(\tR\x12verificationMethod\x12;\n" +
	"\rmetric_checks\x18\x03 \x03(\v2\x16.api.proto.MetricCheckR\fmetricChecks\"\x87\x01\n" +
	"\vMetricCheck\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\x01R\tthreshold\x12!\n" +
	"\factual_value\x18\x03 \x01(\x01R\vactualValue\x12\x16\n" +
	"\x06passed\x18\x04 \x01(\bR\x06passed\"\xef\x01\n" +
	"\fRollbackInfo\x12!\n" +
	"\fcan_rollback\x18\x01 \x01(\bR\vcanRollback\x12'\n" +
	"\x0frollback_method\x18\x02 \x01(\tR\x0erollbackMethod\x12Q\n" +
	"\x0erollback_state\x18\x03 \x03(\v2*.api.proto.RollbackInfo.RollbackStateEntryR\rrollbackState\x1a@\n" +
	"\x12RollbackStateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\a\n" +
	"\x10ActionParameters\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x1f\n" +
	"\vtarget_name\x18\x02 \x01(\tR\n" +
	"targetName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12R\n" +
	"\rstring_params\x18\x04 \x03(\v2-.api.proto.ActionParameters.StringParamsEntryR\fstringParams\x12I\n" +
	"\n" +
	"int_params\x18\x05 \x03(\v2*.api.proto.ActionParameters.IntParamsEntryR\tintParams\x12O\n" +
	"\ffloat_params\x18\x06 \x03(\v2,.api.proto.ActionParameters.FloatParamsEntryR\vfloatParams\x12L\n" +
	"\vbool_params\x18\a \x03(\v2+.api.proto.ActionParameters.BoolParamsEntryR\n" +
	"boolParams\x12\x1a\n" +
	"\breplicas\x18\n" +
	" \x01(\x05R\breplicas\x125\n" +
	"\bresource\x18\v \x01(\v2\x19.api.proto.ResourceAmountR\bresource\x12U\n" +
	"\x0econfig_updates\x18\f \x03(\v2..api.proto.ActionParameters.ConfigUpdatesEntryR\rconfigUpdates\x1a?\n" +
	"\x11StringParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eIntParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a>\n" +
	"\x10FloatParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a=\n" +
	"\x0fBoolParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a@\n" +
	"\x12ConfigUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x0eResourceAmount\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\"\xf4\x03\n" +
	"\x11ActionConstraints\x12#\n" +
	"\rallowed_after\x18\x01 \x01(\x03R\fallowedAfter\x12%\n" +
	"\x0eallowed_before\x18\x02 \x01(\x03R\rallowedBefore\x12+\n" +
	"\x11requires_approval\x18\x03 \x01(\bR\x10requiresApproval\x12\x1c\n" +
	"\tapprovers\x18\x04 \x03(\tR\tapprovers\x12!\n" +
	"\fmax_replicas\x18\x05 \x01(\x05R\vmaxReplicas\x12!\n" +
	"\fmin_replicas\x18\x06 \x01(\x05R\vminReplicas\x12>\n" +
	"\rmax_resources\x18\a \x01(\v2\x19.api.proto.ResourceAmountR\fmaxResources\x12/\n" +
	"\x13required_conditions\x18\b \x03(\tR\x12requiredConditions\x12/\n" +
	"\x13blocking_conditions\x18\t \x03(\tR\x12blockingConditions\x125\n" +
	"\x17max_executions_per_hour\x18\n" +
	" \x01(\x05R\x14maxExecutionsPerHour\x12)\n" +
	"\x10cooldown_seconds\x18\v \x01(\x05R\x0fcooldownSeconds\"\xa3\x01\n" +
	"\rActionRequest\x12)\n" +
	"\x06action\x18\x01 \x01(\v2\x11.api.proto.ActionR\x06action\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x03R\x0etimeoutSeconds\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\"\xab\x01\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\tR\bactionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12,\n" +
	"\x05state\x18\x04 \x01(\x0e2\x16.api.proto.ActionStateR\x05state\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\"\x92\x01\n" +
	"\vActionBatch\x12+\n" +
	"\aactions\x18\x01 \x03(\v2\x11.api.proto.ActionR\aactions\x12-\n" +
	"\x13execute_all_or_none\x18\x02 \x01(\bR\x10executeAllOrNone\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x03R\x0etimeoutSeconds\"\x80\x02\n" +
	"\n" +
	"ActionPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04goal\x18\x04 \x01(\tR\x04goal\x12+\n" +
	"\x05steps\x18\x05 \x03(\v2\x15.api.proto.ActionStepR\x05steps\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.api.proto.PlanStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\x98\x01\n" +
	"\n" +
	"ActionStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x05R\x05order\x12)\n" +
	"\x06action\x18\x03 \x01(\v2\x11.api.proto.ActionR\x06action\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x04 \x03(\tR\tdependsOn\x12\x1a\n" +
	"\boptional\x18\x05 \x01(\bR\boptional\"/\n" +
	"\x10GetActionRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\"\x92\x02\n" +
	"\x12ListActionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x125\n" +
	"\bcategory\x18\x03 \x01(\x0e2\x19.api.proto.ActionCategoryR\bcategory\x12,\n" +
	"\x05state\x18\x04 \x01(\x0e2\x16.api.proto.ActionStateR\x05state\x12#\n" +
	"\rcreated_after\x18\x05 \x01(\x03R\fcreatedAfter\x12%\n" +
	"\x0ecreated_before\x18\x06 \x01(\x03R\rcreatedBefore\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\"c\n" +
	"\x13ListActionsResponse\x12+\n" +
	"\aactions\x18\x01 \x03(\v2\x11.api.proto.ActionR\aactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"J\n" +
	"\x13CancelActionRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\\\n" +
	"\x0fRollbackRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force*\xc0\x02\n" +
	"\x0eActionCategory\x12\x1b\n" +
	"\x17ACTION_CATEGORY_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17ACTION_CATEGORY_SCALING\x10\x01\x12\x1b\n" +
	"\x17ACTION_CATEGORY_RESTART\x10\x02\x12\x1c\n" +
	"\x18ACTION_CATEGORY_FAILOVER\x10\x03\x12\x1c\n" +
	"\x18ACTION_CATEGORY_ROLLBACK\x10\x04\x12!\n" +
	"\x1dACTION_CATEGORY_CONFIG_CHANGE\x10\x05\x12\"\n" +
	"\x1eACTION_CATEGORY_RESOURCE_LIMIT\x10\x06\x12\x1b\n" +
	"\x17ACTION_CATEGORY_NETWORK\x10\a\x12\x1b\n" +
	"\x17ACTION_CATEGORY_STORAGE\x10\b\x12\x1a\n" +
	"\x16ACTION_CATEGORY_CUSTOM\x10c*\x85\x02\n" +
	"\vActionState\x12\x18\n" +
	"\x14ACTION_STATE_PENDING\x10\x00\x12\x1b\n" +
	"\x17ACTION_STATE_VALIDATING\x10\x01\x12\x19\n" +
	"\x15ACTION_STATE_APPROVED\x10\x02\x12\x19\n" +
	"\x15ACTION_STATE_REJECTED\x10\x03\x12\x1a\n" +
	"\x16ACTION_STATE_EXECUTING\x10\x04\x12\x1a\n" +
	"\x16ACTION_STATE_COMPLETED\x10\x05\x12\x17\n" +
	"\x13ACTION_STATE_FAILED\x10\x06\x12\x1c\n" +
	"\x18ACTION_STATE_ROLLED_BACK\x10\a\x12\x1a\n" +
	"\x16ACTION_STATE_CANCELLED\x10\b*\xb5\x01\n" +
	"\n" +
	"PlanStatus\x12\x17\n" +
	"\x13PLAN_STATUS_PENDING\x10\x00\x12\x1b\n" +
	"\x17PLAN_STATUS_IN_PROGRESS\x10\x01\x12\x19\n" +
	"\x15PLAN_STATUS_COMPLETED\x10\x02\x12\x16\n" +
	"\x12PLAN_STATUS_FAILED\x10\x03\x12#\n" +
	"\x1fPLAN_STATUS_PARTIALLY_COMPLETED\x10\x04\x12\x19\n" +
	"\x15PLAN_STATUS_CANCELLED\x10\x052\x85\x04\n" +
	"\x16ActionExecutionService\x12D\n" +
	"\rExecuteAction\x12\x18.api.proto.ActionRequest\x1a\x19.api.proto.ActionResponse\x12C\n" +
	"\fExecuteBatch\x12\x16.api.proto.ActionBatch\x1a\x19.api.proto.ActionResponse0\x01\x12A\n" +
	"\vExecutePlan\x12\x15.api.proto.ActionPlan\x1a\x19.api.proto.ActionResponse0\x01\x12;\n" +
	"\tGetAction\x12\x1b.api.proto.GetActionRequest\x1a\x11.api.proto.Action\x12L\n" +
	"\vListActions\x12\x1d.api.proto.ListActionsRequest\x1a\x1e.api.proto.ListActionsResponse\x12I\n" +
	"\fCancelAction\x12\x1e.api.proto.CancelActionRequest\x1a\x19.api.proto.ActionResponse\x12G\n" +
	"\x0eRollbackAction\x12\x1a.api.proto.RollbackRequest\x1a\x19.api.proto.ActionResponseB7Z5github.com/jfang2048/ai_sre_agent_pub/pkg/proto;protob\x06proto3"

var (
	file_action_proto_rawDescOnce sync.Once
	file_action_proto_rawDescData []byte
)

func file_action_proto_rawDescGZIP() []byte {
	file_action_proto_rawDescOnce.Do(func() {
		file_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_action_proto_rawDesc), len(file_action_proto_rawDesc)))
	})
	return file_action_proto_rawDescData
}

var file_action_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_action_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_action_proto_goTypes = []any{
	(ActionCategory)(0),         // 0: api.proto.ActionCategory
	(ActionState)(0),            // 1: api.proto.ActionState
	(PlanStatus)(0),             // 2: api.proto.PlanStatus
	(*Action)(nil),              // 3: api.proto.Action
	(*ActionResult)(nil),        // 4: api.proto.ActionResult
	(*ChangeSummary)(nil),       // 5: api.proto.ChangeSummary
	(*VerificationResult)(nil),  // 6: api.proto.VerificationResult
	(*MetricCheck)(nil),         // 7: api.proto.MetricCheck
	(*RollbackInfo)(nil),        // 8: api.proto.RollbackInfo
	(*ActionParameters)(nil),    // 9: api.proto.ActionParameters
	(*ResourceAmount)(nil),      // 10: api.proto.ResourceAmount
	(*ActionConstraints)(nil),   // 11: api.proto.ActionConstraints
	(*ActionRequest)(nil),       // 12: api.proto.ActionRequest
	(*ActionResponse)(nil),      // 13: api.proto.ActionResponse
	(*ActionBatch)(nil),         // 14: api.proto.ActionBatch
	(*ActionPlan)(nil),          // 15: api.proto.ActionPlan
	(*ActionStep)(nil),          // 16: api.proto.ActionStep
	(*GetActionRequest)(nil),    // 17: api.proto.GetActionRequest
	(*ListActionsRequest)(nil),  // 18: api.proto.ListActionsRequest
	(*ListActionsResponse)(nil), // 19: api.proto.ListActionsResponse
	(*CancelActionRequest)(nil), // 20: api.proto.CancelActionRequest
	(*RollbackRequest)(nil),     // 21: api.proto.RollbackRequest
	nil,                         // 22: api.proto.RollbackInfo.RollbackStateEntry
	nil,                         // 23: api.proto.ActionParameters.StringParamsEntry
	nil,                         // 24: api.proto.ActionParameters.IntParamsEntry
	nil,                         // 25: api.proto.ActionParameters.FloatParamsEntry
	nil,                         // 26: api.proto.ActionParameters.BoolParamsEntry
	nil,                         // 27: api.proto.ActionParameters.ConfigUpdatesEntry
}
var file_action_proto_depIdxs = []int32{
	0,  // 0: api.proto.Action.category:type_name -> api.proto.ActionCategory
	9,  // 1: api.proto.Action.parameters:type_name -> api.proto.ActionParameters
	11, // 2: api.proto.Action.constraints:type_name -> api.proto.ActionConstraints
	1,  // 3: api.proto.Action.state:type_name -> api.proto.ActionState
	4,  // 4: api.proto.Action.result:type_name -> api.proto.ActionResult
	5,  // 5: api.proto.ActionResult.changes:type_name -> api.proto.ChangeSummary
	6,  // 6: api.proto.ActionResult.verification:type_name -> api.proto.VerificationResult
	8,  // 7: api.proto.ActionResult.rollback:type_name -> api.proto.RollbackInfo
	7,  // 8: api.proto.VerificationResult.metric_checks:type_name -> api.proto.MetricCheck
	22, // 9: api.proto.RollbackInfo.rollback_state:type_name -> api.proto.RollbackInfo.RollbackStateEntry
	23, // 10: api.proto.ActionParameters.string_params:type_name -> api.proto.ActionParameters.StringParamsEntry
	24, // 11: api.proto.ActionParameters.int_params:type_name -> api.proto.ActionParameters.IntParamsEntry
	25, // 12: api.proto.ActionParameters.float_params:type_name -> api.proto.ActionParameters.FloatParamsEntry
	26, // 13: api.proto.ActionParameters.bool_params:type_name -> api.proto.ActionParameters.BoolParamsEntry
	10, // 14: api.proto.ActionParameters.resource:type_name -> api.proto.ResourceAmount
	27, // 15: api.proto.ActionParameters.config_updates:type_name -> api.proto.ActionParameters.ConfigUpdatesEntry
	10, // 16: api.proto.ActionConstraints.max_resources:type_name -> api.proto.ResourceAmount
	3,  // 17: api.proto.ActionRequest.action:type_name -> api.proto.Action
	1,  // 18: api.proto.ActionResponse.state:type_name -> api.proto.ActionState
	3,  // 19: api.proto.ActionBatch.actions:type_name -> api.proto.Action
	16, // 20: api.proto.ActionPlan.steps:type_name -> api.proto.ActionStep
	2,  // 21: api.proto.ActionPlan.status:type_name -> api.proto.PlanStatus
	3,  // 22: api.proto.ActionStep.action:type_name -> api.proto.Action
	0,  // 23: api.proto.ListActionsRequest.category:type_name -> api.proto.ActionCategory
	1,  // 24: api.proto.ListActionsRequest.state:type_name -> api.proto.ActionState
	3,  // 25: api.proto.ListActionsResponse.actions:type_name -> api.proto.Action
	12, // 26: api.proto.ActionExecutionService.ExecuteAction:input_type -> api.proto.ActionRequest
	14, // 27: api.proto.ActionExecutionService.ExecuteBatch:input_type -> api.proto.ActionBatch
	15, // 28: api.proto.ActionExecutionService.ExecutePlan:input_type -> api.proto.ActionPlan
	17, // 29: api.proto.ActionExecutionService.GetAction:input_type -> api.proto.GetActionRequest
	18, // 30: api.proto.ActionExecutionService.ListActions:input_type -> api.proto.ListActionsRequest
	20, // 31: api.proto.ActionExecutionService.CancelAction:input_type -> api.proto.CancelActionRequest
	21, // 32: api.proto.ActionExecutionService.RollbackAction:input_type -> api.proto.RollbackRequest
	13, // 33: api.proto.ActionExecutionService.ExecuteAction:output_type -> api.proto.ActionResponse
	13, // 34: api.proto.ActionExecutionService.ExecuteBatch:output_type -> api.proto.ActionResponse
	13, // 35: api.proto.ActionExecutionService.ExecutePlan:output_type -> api.proto.ActionResponse
	3,  // 36: api.proto.ActionExecutionService.GetAction:output_type -> api.proto.Action
	19, // 37: api.proto.ActionExecutionService.ListActions:output_type -> api.proto.ListActionsResponse
	13, // 38: api.proto.ActionExecutionService.CancelAction:output_type -> api.proto.ActionResponse
	13, // 39: api.proto.ActionExecutionService.RollbackAction:output_type -> api.proto.ActionResponse
	33, // [33:40] is the sub-list for method output_type
	26, // [26:33] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_action_proto_init() }
func file_action_proto_init() {
	if File_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_proto_rawDesc), len(file_action_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_action_proto_goTypes,
		DependencyIndexes: file_action_proto_depIdxs,
		EnumInfos:         file_action_proto_enumTypes,
		MessageInfos:      file_action_proto_msgTypes,
	}.Build()
	File_action_proto = out.File
	file_action_proto_goTypes = nil
	file_action_proto_depIdxs = nil
}
