// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: alerting.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Alert state
type AlertState int32

const (
	AlertState_ALERT_STATE_UNKNOWN      AlertState = 0
	AlertState_ALERT_STATE_PENDING      AlertState = 1
	AlertState_ALERT_STATE_FIRING       AlertState = 2
	AlertState_ALERT_STATE_RESOLVED     AlertState = 3
	AlertState_ALERT_STATE_SUPPRESSED   AlertState = 4
	AlertState_ALERT_STATE_ACKNOWLEDGED AlertState = 5
)

// Enum value maps for AlertState.
var (
	AlertState_name = map[int32]string{
		0: "ALERT_STATE_UNKNOWN",
		1: "ALERT_STATE_PENDING",
		2: "ALERT_STATE_FIRING",
		3: "ALERT_STATE_RESOLVED",
		4: "ALERT_STATE_SUPPRESSED",
		5: "ALERT_STATE_ACKNOWLEDGED",
	}
	AlertState_value = map[string]int32{
		"ALERT_STATE_UNKNOWN":      0,
		"ALERT_STATE_PENDING":      1,
		"ALERT_STATE_FIRING":       2,
		"ALERT_STATE_RESOLVED":     3,
		"ALERT_STATE_SUPPRESSED":   4,
		"ALERT_STATE_ACKNOWLEDGED": 5,
	}
)

func (x AlertState) Enum() *AlertState {
	p := new(AlertState)
	*p = x
	return p
}

func (x AlertState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertState) Descriptor() protoreflect.EnumDescriptor {
	return file_alerting_proto_enumTypes[0].Descriptor()
}

func (AlertState) Type() protoreflect.EnumType {
	return &file_alerting_proto_enumTypes[0]
}

func (x AlertState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertState.Descriptor instead.
func (AlertState) EnumDescriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{0}
}

type ConditionType int32

const (
	ConditionType_CONDITION_TYPE_UNKNOWN    ConditionType = 0
	ConditionType_CONDITION_TYPE_THRESHOLD  ConditionType = 1
	ConditionType_CONDITION_TYPE_PREDICTION ConditionType = 2
	ConditionType_CONDITION_TYPE_ANOMALY    ConditionType = 3
	ConditionType_CONDITION_TYPE_RATE       ConditionType = 4
	ConditionType_CONDITION_TYPE_COMPOSITE  ConditionType = 5
)

// Enum value maps for ConditionType.
var (
	ConditionType_name = map[int32]string{
		0: "CONDITION_TYPE_UNKNOWN",
		1: "CONDITION_TYPE_THRESHOLD",
		2: "CONDITION_TYPE_PREDICTION",
		3: "CONDITION_TYPE_ANOMALY",
		4: "CONDITION_TYPE_RATE",
		5: "CONDITION_TYPE_COMPOSITE",
	}
	ConditionType_value = map[string]int32{
		"CONDITION_TYPE_UNKNOWN":    0,
		"CONDITION_TYPE_THRESHOLD":  1,
		"CONDITION_TYPE_PREDICTION": 2,
		"CONDITION_TYPE_ANOMALY":    3,
		"CONDITION_TYPE_RATE":       4,
		"CONDITION_TYPE_COMPOSITE":  5,
	}
)

func (x ConditionType) Enum() *ConditionType {
	p := new(ConditionType)
	*p = x
	return p
}

func (x ConditionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionType) Descriptor() protoreflect.EnumDescriptor {
	return file_alerting_proto_enumTypes[1].Descriptor()
}

func (ConditionType) Type() protoreflect.EnumType {
	return &file_alerting_proto_enumTypes[1]
}

func (x ConditionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionType.Descriptor instead.
func (ConditionType) EnumDescriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{1}
}

type ThresholdOperator int32

const (
	ThresholdOperator_THRESHOLD_OPERATOR_UNKNOWN          ThresholdOperator = 0
	ThresholdOperator_THRESHOLD_OPERATOR_GREATER_THAN     ThresholdOperator = 1
	ThresholdOperator_THRESHOLD_OPERATOR_LESS_THAN        ThresholdOperator = 2
	ThresholdOperator_THRESHOLD_OPERATOR_EQUAL            ThresholdOperator = 3
	ThresholdOperator_THRESHOLD_OPERATOR_NOT_EQUAL        ThresholdOperator = 4
	ThresholdOperator_THRESHOLD_OPERATOR_GREATER_OR_EQUAL ThresholdOperator = 5
	ThresholdOperator_THRESHOLD_OPERATOR_LESS_OR_EQUAL    ThresholdOperator = 6
)

// Enum value maps for ThresholdOperator.
var (
	ThresholdOperator_name = map[int32]string{
		0: "THRESHOLD_OPERATOR_UNKNOWN",
		1: "THRESHOLD_OPERATOR_GREATER_THAN",
		2: "THRESHOLD_OPERATOR_LESS_THAN",
		3: "THRESHOLD_OPERATOR_EQUAL",
		4: "THRESHOLD_OPERATOR_NOT_EQUAL",
		5: "THRESHOLD_OPERATOR_GREATER_OR_EQUAL",
		6: "THRESHOLD_OPERATOR_LESS_OR_EQUAL",
	}
	ThresholdOperator_value = map[string]int32{
		"THRESHOLD_OPERATOR_UNKNOWN":          0,
		"THRESHOLD_OPERATOR_GREATER_THAN":     1,
		"THRESHOLD_OPERATOR_LESS_THAN":        2,
		"THRESHOLD_OPERATOR_EQUAL":            3,
		"THRESHOLD_OPERATOR_NOT_EQUAL":        4,
		"THRESHOLD_OPERATOR_GREATER_OR_EQUAL": 5,
		"THRESHOLD_OPERATOR_LESS_OR_EQUAL":    6,
	}
)

func (x ThresholdOperator) Enum() *ThresholdOperator {
	p := new(ThresholdOperator)
	*p = x
	return p
}

func (x ThresholdOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThresholdOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_alerting_proto_enumTypes[2].Descriptor()
}

func (ThresholdOperator) Type() protoreflect.EnumType {
	return &file_alerting_proto_enumTypes[2]
}

func (x ThresholdOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThresholdOperator.Descriptor instead.
func (ThresholdOperator) EnumDescriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{2}
}

type AnomalyMethod int32

const (
	AnomalyMethod_ANOMALY_METHOD_UNKNOWN          AnomalyMethod = 0
	AnomalyMethod_ANOMALY_METHOD_Z_SCORE          AnomalyMethod = 1
	AnomalyMethod_ANOMALY_METHOD_MAD              AnomalyMethod = 2 // Median Absolute Deviation
	AnomalyMethod_ANOMALY_METHOD_IQR              AnomalyMethod = 3 // Interquartile Range
	AnomalyMethod_ANOMALY_METHOD_ISOLATION_FOREST AnomalyMethod = 4
)

// Enum value maps for AnomalyMethod.
var (
	AnomalyMethod_name = map[int32]string{
		0: "ANOMALY_METHOD_UNKNOWN",
		1: "ANOMALY_METHOD_Z_SCORE",
		2: "ANOMALY_METHOD_MAD",
		3: "ANOMALY_METHOD_IQR",
		4: "ANOMALY_METHOD_ISOLATION_FOREST",
	}
	AnomalyMethod_value = map[string]int32{
		"ANOMALY_METHOD_UNKNOWN":          0,
		"ANOMALY_METHOD_Z_SCORE":          1,
		"ANOMALY_METHOD_MAD":              2,
		"ANOMALY_METHOD_IQR":              3,
		"ANOMALY_METHOD_ISOLATION_FOREST": 4,
	}
)

func (x AnomalyMethod) Enum() *AnomalyMethod {
	p := new(AnomalyMethod)
	*p = x
	return p
}

func (x AnomalyMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnomalyMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_alerting_proto_enumTypes[3].Descriptor()
}

func (AnomalyMethod) Type() protoreflect.EnumType {
	return &file_alerting_proto_enumTypes[3]
}

func (x AnomalyMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnomalyMethod.Descriptor instead.
func (AnomalyMethod) EnumDescriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{3}
}

type RateWindow int32

const (
	RateWindow_RATE_WINDOW_UNKNOWN RateWindow = 0
	RateWindow_RATE_WINDOW_1M      RateWindow = 1
	RateWindow_RATE_WINDOW_5M      RateWindow = 2
	RateWindow_RATE_WINDOW_15M     RateWindow = 3
	RateWindow_RATE_WINDOW_1H      RateWindow = 4
)

// Enum value maps for RateWindow.
var (
	RateWindow_name = map[int32]string{
		0: "RATE_WINDOW_UNKNOWN",
		1: "RATE_WINDOW_1M",
		2: "RATE_WINDOW_5M",
		3: "RATE_WINDOW_15M",
		4: "RATE_WINDOW_1H",
	}
	RateWindow_value = map[string]int32{
		"RATE_WINDOW_UNKNOWN": 0,
		"RATE_WINDOW_1M":      1,
		"RATE_WINDOW_5M":      2,
		"RATE_WINDOW_15M":     3,
		"RATE_WINDOW_1H":      4,
	}
)

func (x RateWindow) Enum() *RateWindow {
	p := new(RateWindow)
	*p = x
	return p
}

func (x RateWindow) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateWindow) Descriptor() protoreflect.EnumDescriptor {
	return file_alerting_proto_enumTypes[4].Descriptor()
}

func (RateWindow) Type() protoreflect.EnumType {
	return &file_alerting_proto_enumTypes[4]
}

func (x RateWindow) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateWindow.Descriptor instead.
func (RateWindow) EnumDescriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{4}
}

type LogicalOperator int32

const (
	LogicalOperator_LOGICAL_OPERATOR_UNKNOWN LogicalOperator = 0
	LogicalOperator_LOGICAL_OPERATOR_AND     LogicalOperator = 1
	LogicalOperator_LOGICAL_OPERATOR_OR      LogicalOperator = 2
	LogicalOperator_LOGICAL_OPERATOR_NOT     LogicalOperator = 3
)

// Enum value maps for LogicalOperator.
var (
	LogicalOperator_name = map[int32]string{
		0: "LOGICAL_OPERATOR_UNKNOWN",
		1: "LOGICAL_OPERATOR_AND",
		2: "LOGICAL_OPERATOR_OR",
		3: "LOGICAL_OPERATOR_NOT",
	}
	LogicalOperator_value = map[string]int32{
		"LOGICAL_OPERATOR_UNKNOWN": 0,
		"LOGICAL_OPERATOR_AND":     1,
		"LOGICAL_OPERATOR_OR":      2,
		"LOGICAL_OPERATOR_NOT":     3,
	}
)

func (x LogicalOperator) Enum() *LogicalOperator {
	p := new(LogicalOperator)
	*p = x
	return p
}

func (x LogicalOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_alerting_proto_enumTypes[5].Descriptor()
}

func (LogicalOperator) Type() protoreflect.EnumType {
	return &file_alerting_proto_enumTypes[5]
}

func (x LogicalOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalOperator.Descriptor instead.
func (LogicalOperator) EnumDescriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{5}
}

// Alert represents a single alert
type Alert struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Message    string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Severity   Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=api.proto.Severity" json:"severity,omitempty"`
	State      AlertState             `protobuf:"varint,5,opt,name=state,proto3,enum=api.proto.AlertState" json:"state,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ResolvedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	// Labels for grouping and filtering
	Labels map[string]string `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Annotations for additional context
	Annotations map[string]string `protobuf:"bytes,10,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Related metrics
	Metrics []*MetricReference `protobuf:"bytes,11,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// Related events
	Events []*EventReference `protobuf:"bytes,12,rep,name=events,proto3" json:"events,omitempty"`
	// Correlation information
	Correlation *CorrelationInfo `protobuf:"bytes,13,opt,name=correlation,proto3" json:"correlation,omitempty"`
	// SLO context
	SloContext    *SLOContext `protobuf:"bytes,14,opt,name=slo_context,json=sloContext,proto3" json:"slo_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_alerting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{0}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNKNOWN
}

func (x *Alert) GetState() AlertState {
	if x != nil {
		return x.State
	}
	return AlertState_ALERT_STATE_UNKNOWN
}

func (x *Alert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Alert) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Alert) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

func (x *Alert) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Alert) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Alert) GetMetrics() []*MetricReference {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Alert) GetEvents() []*EventReference {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Alert) GetCorrelation() *CorrelationInfo {
	if x != nil {
		return x.Correlation
	}
	return nil
}

func (x *Alert) GetSloContext() *SLOContext {
	if x != nil {
		return x.SloContext
	}
	return nil
}

// MetricReference references a metric related to the alert
type MetricReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricReference) Reset() {
	*x = MetricReference{}
	mi := &file_alerting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricReference) ProtoMessage() {}

func (x *MetricReference) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricReference.ProtoReflect.Descriptor instead.
func (*MetricReference) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{1}
}

func (x *MetricReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricReference) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricReference) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricReference) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// EventReference references an event related to the alert
type EventReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReference) Reset() {
	*x = EventReference{}
	mi := &file_alerting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReference) ProtoMessage() {}

func (x *EventReference) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReference.ProtoReflect.Descriptor instead.
func (*EventReference) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{2}
}

func (x *EventReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventReference) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventReference) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EventReference) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// CorrelationInfo contains information about correlated alerts/events
type CorrelationInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId   string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	RelatedAlertIds []string               `protobuf:"bytes,2,rep,name=related_alert_ids,json=relatedAlertIds,proto3" json:"related_alert_ids,omitempty"`
	ConfidenceScore float64                `protobuf:"fixed64,3,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	CorrelationType string                 `protobuf:"bytes,4,opt,name=correlation_type,json=correlationType,proto3" json:"correlation_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CorrelationInfo) Reset() {
	*x = CorrelationInfo{}
	mi := &file_alerting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelationInfo) ProtoMessage() {}

func (x *CorrelationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelationInfo.ProtoReflect.Descriptor instead.
func (*CorrelationInfo) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{3}
}

func (x *CorrelationInfo) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CorrelationInfo) GetRelatedAlertIds() []string {
	if x != nil {
		return x.RelatedAlertIds
	}
	return nil
}

func (x *CorrelationInfo) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *CorrelationInfo) GetCorrelationType() string {
	if x != nil {
		return x.CorrelationType
	}
	return ""
}

// SLOContext provides SLO-related context for the alert
type SLOContext struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SloName              string                 `protobuf:"bytes,1,opt,name=slo_name,json=sloName,proto3" json:"slo_name,omitempty"`
	SliValue             float64                `protobuf:"fixed64,2,opt,name=sli_value,json=sliValue,proto3" json:"sli_value,omitempty"`
	Target               float64                `protobuf:"fixed64,3,opt,name=target,proto3" json:"target,omitempty"`
	ErrorBudgetRemaining float64                `protobuf:"fixed64,4,opt,name=error_budget_remaining,json=errorBudgetRemaining,proto3" json:"error_budget_remaining,omitempty"`
	BurnRate             float64                `protobuf:"fixed64,5,opt,name=burn_rate,json=burnRate,proto3" json:"burn_rate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SLOContext) Reset() {
	*x = SLOContext{}
	mi := &file_alerting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLOContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLOContext) ProtoMessage() {}

func (x *SLOContext) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLOContext.ProtoReflect.Descriptor instead.
func (*SLOContext) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{4}
}

func (x *SLOContext) GetSloName() string {
	if x != nil {
		return x.SloName
	}
	return ""
}

func (x *SLOContext) GetSliValue() float64 {
	if x != nil {
		return x.SliValue
	}
	return 0
}

func (x *SLOContext) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *SLOContext) GetErrorBudgetRemaining() float64 {
	if x != nil {
		return x.ErrorBudgetRemaining
	}
	return 0
}

func (x *SLOContext) GetBurnRate() float64 {
	if x != nil {
		return x.BurnRate
	}
	return 0
}

// AlertRule defines when to trigger an alert
type AlertRule struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Condition evaluation
	Condition *Condition `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	// Alert settings
	Severity            Severity `protobuf:"varint,5,opt,name=severity,proto3,enum=api.proto.Severity" json:"severity,omitempty"`
	SummaryTemplate     string   `protobuf:"bytes,6,opt,name=summary_template,json=summaryTemplate,proto3" json:"summary_template,omitempty"`
	DescriptionTemplate string   `protobuf:"bytes,7,opt,name=description_template,json=descriptionTemplate,proto3" json:"description_template,omitempty"`
	// Labels to add to alerts from this rule
	Labels map[string]string `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Annotations to add to alerts from this rule
	Annotations map[string]string `protobuf:"bytes,9,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Suppression settings
	Suppression *SuppressionConfig `protobuf:"bytes,10,opt,name=suppression,proto3" json:"suppression,omitempty"`
	// SLO reference
	SloName       string `protobuf:"bytes,11,opt,name=slo_name,json=sloName,proto3" json:"slo_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRule) Reset() {
	*x = AlertRule{}
	mi := &file_alerting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRule) ProtoMessage() {}

func (x *AlertRule) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRule.ProtoReflect.Descriptor instead.
func (*AlertRule) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{5}
}

func (x *AlertRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AlertRule) GetCondition() *Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *AlertRule) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNKNOWN
}

func (x *AlertRule) GetSummaryTemplate() string {
	if x != nil {
		return x.SummaryTemplate
	}
	return ""
}

func (x *AlertRule) GetDescriptionTemplate() string {
	if x != nil {
		return x.DescriptionTemplate
	}
	return ""
}

func (x *AlertRule) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AlertRule) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *AlertRule) GetSuppression() *SuppressionConfig {
	if x != nil {
		return x.Suppression
	}
	return nil
}

func (x *AlertRule) GetSloName() string {
	if x != nil {
		return x.SloName
	}
	return ""
}

// Condition defines when to trigger an alert
type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ConditionType          `protobuf:"varint,1,opt,name=type,proto3,enum=api.proto.ConditionType" json:"type,omitempty"`
	// Types that are valid to be assigned to Condition:
	//
	//	*Condition_Threshold
	//	*Condition_Prediction
	//	*Condition_Anomaly
	//	*Condition_Rate
	//	*Condition_Composite
	Condition     isCondition_Condition `protobuf_oneof:"condition"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_alerting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{6}
}

func (x *Condition) GetType() ConditionType {
	if x != nil {
		return x.Type
	}
	return ConditionType_CONDITION_TYPE_UNKNOWN
}

func (x *Condition) GetCondition() isCondition_Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *Condition) GetThreshold() *ThresholdCondition {
	if x != nil {
		if x, ok := x.Condition.(*Condition_Threshold); ok {
			return x.Threshold
		}
	}
	return nil
}

func (x *Condition) GetPrediction() *PredictionCondition {
	if x != nil {
		if x, ok := x.Condition.(*Condition_Prediction); ok {
			return x.Prediction
		}
	}
	return nil
}

func (x *Condition) GetAnomaly() *AnomalyCondition {
	if x != nil {
		if x, ok := x.Condition.(*Condition_Anomaly); ok {
			return x.Anomaly
		}
	}
	return nil
}

func (x *Condition) GetRate() *RateCondition {
	if x != nil {
		if x, ok := x.Condition.(*Condition_Rate); ok {
			return x.Rate
		}
	}
	return nil
}

func (x *Condition) GetComposite() *CompositeCondition {
	if x != nil {
		if x, ok := x.Condition.(*Condition_Composite); ok {
			return x.Composite
		}
	}
	return nil
}

type isCondition_Condition interface {
	isCondition_Condition()
}

type Condition_Threshold struct {
	Threshold *ThresholdCondition `protobuf:"bytes,2,opt,name=threshold,proto3,oneof"`
}

type Condition_Prediction struct {
	Prediction *PredictionCondition `protobuf:"bytes,3,opt,name=prediction,proto3,oneof"`
}

type Condition_Anomaly struct {
	Anomaly *AnomalyCondition `protobuf:"bytes,4,opt,name=anomaly,proto3,oneof"`
}

type Condition_Rate struct {
	Rate *RateCondition `protobuf:"bytes,5,opt,name=rate,proto3,oneof"`
}

type Condition_Composite struct {
	Composite *CompositeCondition `protobuf:"bytes,6,opt,name=composite,proto3,oneof"`
}

func (*Condition_Threshold) isCondition_Condition() {}

func (*Condition_Prediction) isCondition_Condition() {}

func (*Condition_Anomaly) isCondition_Condition() {}

func (*Condition_Rate) isCondition_Condition() {}

func (*Condition_Composite) isCondition_Condition() {}

// ThresholdCondition triggers when a metric crosses a threshold
type ThresholdCondition struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Metric          string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Threshold       float64                `protobuf:"fixed64,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Operator        ThresholdOperator      `protobuf:"varint,3,opt,name=operator,proto3,enum=api.proto.ThresholdOperator" json:"operator,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThresholdCondition) Reset() {
	*x = ThresholdCondition{}
	mi := &file_alerting_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThresholdCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdCondition) ProtoMessage() {}

func (x *ThresholdCondition) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdCondition.ProtoReflect.Descriptor instead.
func (*ThresholdCondition) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{7}
}

func (x *ThresholdCondition) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *ThresholdCondition) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *ThresholdCondition) GetOperator() ThresholdOperator {
	if x != nil {
		return x.Operator
	}
	return ThresholdOperator_THRESHOLD_OPERATOR_UNKNOWN
}

func (x *ThresholdCondition) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// PredictionCondition triggers when a prediction indicates a breach
type PredictionCondition struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Metric              string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	PredictionThreshold float64                `protobuf:"fixed64,2,opt,name=prediction_threshold,json=predictionThreshold,proto3" json:"prediction_threshold,omitempty"`
	TimeHorizonSeconds  int32                  `protobuf:"varint,3,opt,name=time_horizon_seconds,json=timeHorizonSeconds,proto3" json:"time_horizon_seconds,omitempty"`
	ConfidenceThreshold float64                `protobuf:"fixed64,4,opt,name=confidence_threshold,json=confidenceThreshold,proto3" json:"confidence_threshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PredictionCondition) Reset() {
	*x = PredictionCondition{}
	mi := &file_alerting_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionCondition) ProtoMessage() {}

func (x *PredictionCondition) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionCondition.ProtoReflect.Descriptor instead.
func (*PredictionCondition) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{8}
}

func (x *PredictionCondition) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *PredictionCondition) GetPredictionThreshold() float64 {
	if x != nil {
		return x.PredictionThreshold
	}
	return 0
}

func (x *PredictionCondition) GetTimeHorizonSeconds() int32 {
	if x != nil {
		return x.TimeHorizonSeconds
	}
	return 0
}

func (x *PredictionCondition) GetConfidenceThreshold() float64 {
	if x != nil {
		return x.ConfidenceThreshold
	}
	return 0
}

// AnomalyCondition triggers when anomaly detection finds unusual patterns
type AnomalyCondition struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Metric                string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	AnomalyScoreThreshold float64                `protobuf:"fixed64,2,opt,name=anomaly_score_threshold,json=anomalyScoreThreshold,proto3" json:"anomaly_score_threshold,omitempty"`
	LookbackSeconds       int32                  `protobuf:"varint,3,opt,name=lookback_seconds,json=lookbackSeconds,proto3" json:"lookback_seconds,omitempty"`
	Method                AnomalyMethod          `protobuf:"varint,4,opt,name=method,proto3,enum=api.proto.AnomalyMethod" json:"method,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AnomalyCondition) Reset() {
	*x = AnomalyCondition{}
	mi := &file_alerting_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyCondition) ProtoMessage() {}

func (x *AnomalyCondition) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyCondition.ProtoReflect.Descriptor instead.
func (*AnomalyCondition) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{9}
}

func (x *AnomalyCondition) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *AnomalyCondition) GetAnomalyScoreThreshold() float64 {
	if x != nil {
		return x.AnomalyScoreThreshold
	}
	return 0
}

func (x *AnomalyCondition) GetLookbackSeconds() int32 {
	if x != nil {
		return x.LookbackSeconds
	}
	return 0
}

func (x *AnomalyCondition) GetMethod() AnomalyMethod {
	if x != nil {
		return x.Method
	}
	return AnomalyMethod_ANOMALY_METHOD_UNKNOWN
}

// RateCondition triggers based on rate of change
type RateCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	RateThreshold float64                `protobuf:"fixed64,2,opt,name=rate_threshold,json=rateThreshold,proto3" json:"rate_threshold,omitempty"`
	Window        RateWindow             `protobuf:"varint,3,opt,name=window,proto3,enum=api.proto.RateWindow" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateCondition) Reset() {
	*x = RateCondition{}
	mi := &file_alerting_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateCondition) ProtoMessage() {}

func (x *RateCondition) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateCondition.ProtoReflect.Descriptor instead.
func (*RateCondition) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{10}
}

func (x *RateCondition) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *RateCondition) GetRateThreshold() float64 {
	if x != nil {
		return x.RateThreshold
	}
	return 0
}

func (x *RateCondition) GetWindow() RateWindow {
	if x != nil {
		return x.Window
	}
	return RateWindow_RATE_WINDOW_UNKNOWN
}

// CompositeCondition combines multiple conditions
type CompositeCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*Condition           `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Operator      LogicalOperator        `protobuf:"varint,2,opt,name=operator,proto3,enum=api.proto.LogicalOperator" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeCondition) Reset() {
	*x = CompositeCondition{}
	mi := &file_alerting_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeCondition) ProtoMessage() {}

func (x *CompositeCondition) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeCondition.ProtoReflect.Descriptor instead.
func (*CompositeCondition) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{11}
}

func (x *CompositeCondition) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *CompositeCondition) GetOperator() LogicalOperator {
	if x != nil {
		return x.Operator
	}
	return LogicalOperator_LOGICAL_OPERATOR_UNKNOWN
}

// SuppressionConfig controls alert suppression
type SuppressionConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SuppressForSeconds int32                  `protobuf:"varint,1,opt,name=suppress_for_seconds,json=suppressForSeconds,proto3" json:"suppress_for_seconds,omitempty"`
	MaxAlertsPerHour   int32                  `protobuf:"varint,2,opt,name=max_alerts_per_hour,json=maxAlertsPerHour,proto3" json:"max_alerts_per_hour,omitempty"`
	GroupSimilar       bool                   `protobuf:"varint,3,opt,name=group_similar,json=groupSimilar,proto3" json:"group_similar,omitempty"`
	GroupByLabels      []string               `protobuf:"bytes,4,rep,name=group_by_labels,json=groupByLabels,proto3" json:"group_by_labels,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SuppressionConfig) Reset() {
	*x = SuppressionConfig{}
	mi := &file_alerting_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuppressionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuppressionConfig) ProtoMessage() {}

func (x *SuppressionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuppressionConfig.ProtoReflect.Descriptor instead.
func (*SuppressionConfig) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{12}
}

func (x *SuppressionConfig) GetSuppressForSeconds() int32 {
	if x != nil {
		return x.SuppressForSeconds
	}
	return 0
}

func (x *SuppressionConfig) GetMaxAlertsPerHour() int32 {
	if x != nil {
		return x.MaxAlertsPerHour
	}
	return 0
}

func (x *SuppressionConfig) GetGroupSimilar() bool {
	if x != nil {
		return x.GroupSimilar
	}
	return false
}

func (x *SuppressionConfig) GetGroupByLabels() []string {
	if x != nil {
		return x.GroupByLabels
	}
	return nil
}

// AlertNotification represents a notification sent to external systems
type AlertNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AlertId       string                 `protobuf:"bytes,2,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RetryCount    int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertNotification) Reset() {
	*x = AlertNotification{}
	mi := &file_alerting_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertNotification) ProtoMessage() {}

func (x *AlertNotification) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertNotification.ProtoReflect.Descriptor instead.
func (*AlertNotification) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{13}
}

func (x *AlertNotification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertNotification) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *AlertNotification) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *AlertNotification) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *AlertNotification) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AlertNotification) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AlertNotification) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

// NotificationChannel represents a destination for alerts
type NotificationChannel struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type    string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Enabled bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Config  map[string]string      `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Filter for which alerts to send
	AcceptedSeverities []Severity `protobuf:"varint,6,rep,packed,name=accepted_severities,json=acceptedSeverities,proto3,enum=api.proto.Severity" json:"accepted_severities,omitempty"`
	LabelFilters       []string   `protobuf:"bytes,7,rep,name=label_filters,json=labelFilters,proto3" json:"label_filters,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NotificationChannel) Reset() {
	*x = NotificationChannel{}
	mi := &file_alerting_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationChannel) ProtoMessage() {}

func (x *NotificationChannel) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationChannel.ProtoReflect.Descriptor instead.
func (*NotificationChannel) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{14}
}

func (x *NotificationChannel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotificationChannel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationChannel) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NotificationChannel) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *NotificationChannel) GetAcceptedSeverities() []Severity {
	if x != nil {
		return x.AcceptedSeverities
	}
	return nil
}

func (x *NotificationChannel) GetLabelFilters() []string {
	if x != nil {
		return x.LabelFilters
	}
	return nil
}

type EvaluateRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleIds       []string               `protobuf:"bytes,1,rep,name=rule_ids,json=ruleIds,proto3" json:"rule_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRulesRequest) Reset() {
	*x = EvaluateRulesRequest{}
	mi := &file_alerting_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRulesRequest) ProtoMessage() {}

func (x *EvaluateRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRulesRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRulesRequest) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{15}
}

func (x *EvaluateRulesRequest) GetRuleIds() []string {
	if x != nil {
		return x.RuleIds
	}
	return nil
}

type EvaluateRulesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Alerts         []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	RulesEvaluated int32                  `protobuf:"varint,2,opt,name=rules_evaluated,json=rulesEvaluated,proto3" json:"rules_evaluated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvaluateRulesResponse) Reset() {
	*x = EvaluateRulesResponse{}
	mi := &file_alerting_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRulesResponse) ProtoMessage() {}

func (x *EvaluateRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRulesResponse.ProtoReflect.Descriptor instead.
func (*EvaluateRulesResponse) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{16}
}

func (x *EvaluateRulesResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *EvaluateRulesResponse) GetRulesEvaluated() int32 {
	if x != nil {
		return x.RulesEvaluated
	}
	return 0
}

type GetAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRequest) Reset() {
	*x = GetAlertRequest{}
	mi := &file_alerting_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRequest) ProtoMessage() {}

func (x *GetAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRequest) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{17}
}

func (x *GetAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	States        []AlertState           `protobuf:"varint,3,rep,packed,name=states,proto3,enum=api.proto.AlertState" json:"states,omitempty"`
	Severities    []Severity             `protobuf:"varint,4,rep,packed,name=severities,proto3,enum=api.proto.Severity" json:"severities,omitempty"`
	LabelMatcher  map[string]string      `protobuf:"bytes,5,rep,name=label_matcher,json=labelMatcher,proto3" json:"label_matcher,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsRequest) Reset() {
	*x = ListAlertsRequest{}
	mi := &file_alerting_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsRequest) ProtoMessage() {}

func (x *ListAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListAlertsRequest) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{18}
}

func (x *ListAlertsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListAlertsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListAlertsRequest) GetStates() []AlertState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ListAlertsRequest) GetSeverities() []Severity {
	if x != nil {
		return x.Severities
	}
	return nil
}

func (x *ListAlertsRequest) GetLabelMatcher() map[string]string {
	if x != nil {
		return x.LabelMatcher
	}
	return nil
}

func (x *ListAlertsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAlertsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsResponse) Reset() {
	*x = ListAlertsResponse{}
	mi := &file_alerting_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsResponse) ProtoMessage() {}

func (x *ListAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertsResponse) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{19}
}

func (x *ListAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *ListAlertsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAlertsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type AcknowledgeAlertRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AcknowledgedBy string                 `protobuf:"bytes,2,opt,name=acknowledged_by,json=acknowledgedBy,proto3" json:"acknowledged_by,omitempty"`
	Comment        string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcknowledgeAlertRequest) Reset() {
	*x = AcknowledgeAlertRequest{}
	mi := &file_alerting_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeAlertRequest) ProtoMessage() {}

func (x *AcknowledgeAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeAlertRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeAlertRequest) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{20}
}

func (x *AcknowledgeAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AcknowledgeAlertRequest) GetAcknowledgedBy() string {
	if x != nil {
		return x.AcknowledgedBy
	}
	return ""
}

func (x *AcknowledgeAlertRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type AcknowledgeAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeAlertResponse) Reset() {
	*x = AcknowledgeAlertResponse{}
	mi := &file_alerting_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeAlertResponse) ProtoMessage() {}

func (x *AcknowledgeAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeAlertResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeAlertResponse) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{21}
}

func (x *AcknowledgeAlertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResolveAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResolvedBy    string                 `protobuf:"bytes,2,opt,name=resolved_by,json=resolvedBy,proto3" json:"resolved_by,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAlertRequest) Reset() {
	*x = ResolveAlertRequest{}
	mi := &file_alerting_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAlertRequest) ProtoMessage() {}

func (x *ResolveAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAlertRequest.ProtoReflect.Descriptor instead.
func (*ResolveAlertRequest) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{22}
}

func (x *ResolveAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResolveAlertRequest) GetResolvedBy() string {
	if x != nil {
		return x.ResolvedBy
	}
	return ""
}

func (x *ResolveAlertRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ResolveAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAlertResponse) Reset() {
	*x = ResolveAlertResponse{}
	mi := &file_alerting_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAlertResponse) ProtoMessage() {}

func (x *ResolveAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAlertResponse.ProtoReflect.Descriptor instead.
func (*ResolveAlertResponse) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{23}
}

func (x *ResolveAlertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StreamAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinSeverity   []Severity             `protobuf:"varint,1,rep,packed,name=min_severity,json=minSeverity,proto3,enum=api.proto.Severity" json:"min_severity,omitempty"`
	LabelMatcher  map[string]string      `protobuf:"bytes,2,rep,name=label_matcher,json=labelMatcher,proto3" json:"label_matcher,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAlertsRequest) Reset() {
	*x = StreamAlertsRequest{}
	mi := &file_alerting_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAlertsRequest) ProtoMessage() {}

func (x *StreamAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAlertsRequest.ProtoReflect.Descriptor instead.
func (*StreamAlertsRequest) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{24}
}

func (x *StreamAlertsRequest) GetMinSeverity() []Severity {
	if x != nil {
		return x.MinSeverity
	}
	return nil
}

func (x *StreamAlertsRequest) GetLabelMatcher() map[string]string {
	if x != nil {
		return x.LabelMatcher
	}
	return nil
}

type CreateAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *AlertRule             `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRuleRequest) Reset() {
	*x = CreateAlertRuleRequest{}
	mi := &file_alerting_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRuleRequest) ProtoMessage() {}

func (x *CreateAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{25}
}

func (x *CreateAlertRuleRequest) GetRule() *AlertRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type UpdateAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rule          *AlertRule             `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertRuleRequest) Reset() {
	*x = UpdateAlertRuleRequest{}
	mi := &file_alerting_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertRuleRequest) ProtoMessage() {}

func (x *UpdateAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateAlertRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetRule() *AlertRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type DeleteAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertRuleRequest) Reset() {
	*x = DeleteAlertRuleRequest{}
	mi := &file_alerting_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertRuleRequest) ProtoMessage() {}

func (x *DeleteAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteAlertRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertRuleResponse) Reset() {
	*x = DeleteAlertRuleResponse{}
	mi := &file_alerting_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertRuleResponse) ProtoMessage() {}

func (x *DeleteAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteAlertRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListAlertRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnabledOnly   bool                   `protobuf:"varint,1,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertRulesRequest) Reset() {
	*x = ListAlertRulesRequest{}
	mi := &file_alerting_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertRulesRequest) ProtoMessage() {}

func (x *ListAlertRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertRulesRequest.ProtoReflect.Descriptor instead.
func (*ListAlertRulesRequest) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{29}
}

func (x *ListAlertRulesRequest) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

type ListAlertRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*AlertRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertRulesResponse) Reset() {
	*x = ListAlertRulesResponse{}
	mi := &file_alerting_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertRulesResponse) ProtoMessage() {}

func (x *ListAlertRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertRulesResponse.ProtoReflect.Descriptor instead.
func (*ListAlertRulesResponse) Descriptor() ([]byte, []int) {
	return file_alerting_proto_rawDescGZIP(), []int{30}
}

func (x *ListAlertRulesResponse) GetRules() []*AlertRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_alerting_proto protoreflect.FileDescriptor

const file_alerting_proto_rawDesc = "" +
	"\n" +
	"\x0ealerting.proto\x12\tapi.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xab\x06\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12/\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x13.api.proto.SeverityR\bseverity\x12+\n" +
	"\x05state\x18\x05 \x01(\x0e2\x15.api.proto.AlertStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\vresolved_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\x124\n" +
	"\x06labels\x18\t \x03(\v2\x1c.api.proto.Alert.LabelsEntryR\x06labels\x12C\n" +
	"\vannotations\x18\n" +
	" \x03(\v2!.api.proto.Alert.AnnotationsEntryR\vannotations\x124\n" +
	"\ametrics\x18\v \x03(\v2\x1a.api.proto.MetricReferenceR\ametrics\x121\n" +
	"\x06events\x18\f \x03(\v2\x19.api.proto.EventReferenceR\x06events\x12<\n" +
	"\vcorrelation\x18\r \x01(\v2\x1a.api.proto.CorrelationInfoR\vcorrelation\x126\n" +
	"\vslo_context\x18\x0e \x01(\v2\x15.api.proto.SLOContextR\n" +
	"sloContext\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf0\x01\n" +
	"\x0fMetricReference\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12>\n" +
	"\x06labels\x18\x04 \x03(\v2&.api.proto.MetricReference.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\x0eEventReference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xba\x01\n" +
	"\x0fCorrelationInfo\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12*\n" +
	"\x11related_alert_ids\x18\x02 \x03(\tR\x0frelatedAlertIds\x12)\n" +
	"\x10confidence_score\x18\x03 \x01(\x01R\x0fconfidenceScore\x12)\n" +
	"\x10correlation_type\x18\x04 \x01(\tR\x0fcorrelationType\"\xaf\x01\n" +
	"\n" +
	"SLOContext\x12\x19\n" +
	"\bslo_name\x18\x01 \x01(\tR\asloName\x12\x1b\n" +
	"\tsli_value\x18\x02 \x01(\x01R\bsliValue\x12\x16\n" +
	"\x06target\x18\x03 \x01(\x01R\x06target\x124\n" +
	"\x16error_budget_remaining\x18\x04 \x01(\x01R\x14errorBudgetRemaining\x12\x1b\n" +
	"\tburn_rate\x18\x05 \x01(\x01R\bburnRate\"\xe5\x04\n" +
	"\tAlertRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x122\n" +
	"\tcondition\x18\x04 \x01(\v2\x14.api.proto.ConditionR\tcondition\x12/\n" +
	"\bseverity\x18\x05 \x01(\x0e2\x13.api.proto.SeverityR\bseverity\x12)\n" +
	"\x10summary_template\x18\x06 \x01(\tR\x0fsummaryTemplate\x121\n" +
	"\x14description_template\x18\a \x01(\tR\x13descriptionTemplate\x128\n" +
	"\x06labels\x18\b \x03(\v2 .api.proto.AlertRule.LabelsEntryR\x06labels\x12G\n" +
	"\vannotations\x18\t \x03(\v2%.api.proto.AlertRule.AnnotationsEntryR\vannotations\x12>\n" +
	"\vsuppression\x18\n" +
	" \x01(\v2\x1c.api.proto.SuppressionConfigR\vsuppression\x12\x19\n" +
	"\bslo_name\x18\v \x01(\tR\asloName\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x02\n" +
	"\tCondition\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.api.proto.ConditionTypeR\x04type\x12=\n" +
	"\tthreshold\x18\x02 \x01(\v2\x1d.api.proto.ThresholdConditionH\x00R\tthreshold\x12@\n" +
	"\n" +
	"prediction\x18\x03 \x01(\v2\x1e.api.proto.PredictionConditionH\x00R\n" +
	"prediction\x127\n" +
	"\aanomaly\x18\x04 \x01(\v2\x1b.api.proto.AnomalyConditionH\x00R\aanomaly\x12.\n" +
	"\x04rate\x18\x05 \x01(\v2\x18.api.proto.RateConditionH\x00R\x04rate\x12=\n" +
	"\tcomposite\x18\x06 \x01(\v2\x1d.api.proto.CompositeConditionH\x00R\tcompositeB\v\n" +
	"\tcondition\"\xaf\x01\n" +
	"\x12ThresholdCondition\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\x01R\tthreshold\x128\n" +
	"\boperator\x18\x03 \x01(\x0e2\x1c.api.proto.ThresholdOperatorR\boperator\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x05R\x0fdurationSeconds\"\xc5\x01\n" +
	"\x13PredictionCondition\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x121\n" +
	"\x14prediction_threshold\x18\x02 \x01(\x01R\x13predictionThreshold\x120\n" +
	"\x14time_horizon_seconds\x18\x03 \x01(\x05R\x12timeHorizonSeconds\x121\n" +
	"\x14confidence_threshold\x18\x04 \x01(\x01R\x13confidenceThreshold\"\xbf\x01\n" +
	"\x10AnomalyCondition\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x126\n" +
	"\x17anomaly_score_threshold\x18\x02 \x01(\x01R\x15anomalyScoreThreshold\x12)\n" +
	"\x10lookback_seconds\x18\x03 \x01(\x05R\x0flookbackSeconds\x120\n" +
	"\x06method\x18\x04 \x01(\x0e2\x18.api.proto.AnomalyMethodR\x06method\"}\n" +
	"\rRateCondition\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12%\n" +
	"\x0erate_threshold\x18\x02 \x01(\x01R\rrateThreshold\x12-\n" +
	"\x06window\x18\x03 \x01(\x0e2\x15.api.proto.RateWindowR\x06window\"\x82\x01\n" +
	"\x12CompositeCondition\x124\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x14.api.proto.ConditionR\n" +
	"conditions\x126\n" +
	"\boperator\x18\x02 \x01(\x0e2\x1a.api.proto.LogicalOperatorR\boperator\"\xc1\x01\n" +
	"\x11SuppressionConfig\x120\n" +
	"\x14suppress_for_seconds\x18\x01 \x01(\x05R\x12suppressForSeconds\x12-\n" +
	"\x13max_alerts_per_hour\x18\x02 \x01(\x05R\x10maxAlertsPerHour\x12#\n" +
	"\rgroup_similar\x18\x03 \x01(\bR\fgroupSimilar\x12&\n" +
	"\x0fgroup_by_labels\x18\x04 \x03(\tR\rgroupByLabels\"\xed\x01\n" +
	"\x11AlertNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\balert_id\x18\x02 \x01(\tR\aalertId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x123\n" +
	"\asent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x05R\n" +
	"retryCount\"\xd1\x02\n" +
	"\x13NotificationChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12B\n" +
	"\x06config\x18\x05 \x03(\v2*.api.proto.NotificationChannel.ConfigEntryR\x06config\x12D\n" +
	"\x13accepted_severities\x18\x06 \x03(\x0e2\x13.api.proto.SeverityR\x12acceptedSeverities\x12#\n" +
	"\rlabel_filters\x18\a \x03(\tR\flabelFilters\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\x14EvaluateRulesRequest\x12\x19\n" +
	"\brule_ids\x18\x01 \x03(\tR\aruleIds\"j\n" +
	"\x15EvaluateRulesResponse\x12(\n" +
	"\x06alerts\x18\x01 \x03(\v2\x10.api.proto.AlertR\x06alerts\x12'\n" +
	"\x0frules_evaluated\x18\x02 \x01(\x05R\x0erulesEvaluated\"!\n" +
	"\x0fGetAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xbb\x03\n" +
	"\x11ListAlertsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12-\n" +
	"\x06states\x18\x03 \x03(\x0e2\x15.api.proto.AlertStateR\x06states\x123\n" +
	"\n" +
	"severities\x18\x04 \x03(\x0e2\x13.api.proto.SeverityR\n" +
	"severities\x12S\n" +
	"\rlabel_matcher\x18\x05 \x03(\v2..api.proto.ListAlertsRequest.LabelMatcherEntryR\flabelMatcher\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\tR\tpageToken\x1a?\n" +
	"\x11LabelMatcherEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x12ListAlertsResponse\x12(\n" +
	"\x06alerts\x18\x01 \x03(\v2\x10.api.proto.AlertR\x06alerts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"l\n" +
	"\x17AcknowledgeAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0facknowledged_by\x18\x02 \x01(\tR\x0eacknowledgedBy\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"4\n" +
	"\x18AcknowledgeAlertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"`\n" +
	"\x13ResolveAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vresolved_by\x18\x02 \x01(\tR\n" +
	"resolvedBy\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"0\n" +
	"\x14ResolveAlertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe5\x01\n" +
	"\x13StreamAlertsRequest\x126\n" +
	"\fmin_severity\x18\x01 \x03(\x0e2\x13.api.proto.SeverityR\vminSeverity\x12U\n" +
	"\rlabel_matcher\x18\x02 \x03(\v20.api.proto.StreamAlertsRequest.LabelMatcherEntryR\flabelMatcher\x1a?\n" +
	"\x11LabelMatcherEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x16CreateAlertRuleRequest\x12(\n" +
	"\x04rule\x18\x01 \x01(\v2\x14.api.proto.AlertRuleR\x04rule\"R\n" +
	"\x16UpdateAlertRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04rule\x18\x02 \x01(\v2\x14.api.proto.AlertRuleR\x04rule\"(\n" +
	"\x16DeleteAlertRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x17DeleteAlertRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x15ListAlertRulesRequest\x12!\n" +
	"\fenabled_only\x18\x01 \x01(\bR\venabledOnly\"D\n" +
	"\x16ListAlertRulesResponse\x12*\n" +
	"\x05rules\x18\x01 \x03(\v2\x14.api.proto.AlertRuleR\x05rules*\xaa\x01\n" +
	"\n" +
	"AlertState\x12\x17\n" +
	"\x13ALERT_STATE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13ALERT_STATE_PENDING\x10\x01\x12\x16\n" +
	"\x12ALERT_STATE_FIRING\x10\x02\x12\x18\n" +
	"\x14ALERT_STATE_RESOLVED\x10\x03\x12\x1a\n" +
	"\x16ALERT_STATE_SUPPRESSED\x10\x04\x12\x1c\n" +
	"\x18ALERT_STATE_ACKNOWLEDGED\x10\x05*\xbb\x01\n" +
	"\rConditionType\x12\x1a\n" +
	"\x16CONDITION_TYPE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18CONDITION_TYPE_THRESHOLD\x10\x01\x12\x1d\n" +
	"\x19CONDITION_TYPE_PREDICTION\x10\x02\x12\x1a\n" +
	"\x16CONDITION_TYPE_ANOMALY\x10\x03\x12\x17\n" +
	"\x13CONDITION_TYPE_RATE\x10\x04\x12\x1c\n" +
	"\x18CONDITION_TYPE_COMPOSITE\x10\x05*\x89\x02\n" +
	"\x11ThresholdOperator\x12\x1e\n" +
	"\x1aTHRESHOLD_OPERATOR_UNKNOWN\x10\x00\x12#\n" +
	"\x1fTHRESHOLD_OPERATOR_GREATER_THAN\x10\x01\x12 \n" +
	"\x1cTHRESHOLD_OPERATOR_LESS_THAN\x10\x02\x12\x1c\n" +
	"\x18THRESHOLD_OPERATOR_EQUAL\x10\x03\x12 \n" +
	"\x1cTHRESHOLD_OPERATOR_NOT_EQUAL\x10\x04\x12'\n" +
	"#THRESHOLD_OPERATOR_GREATER_OR_EQUAL\x10\x05\x12$\n" +
	" THRESHOLD_OPERATOR_LESS_OR_EQUAL\x10\x06*\x9c\x01\n" +
	"\rAnomalyMethod\x12\x1a\n" +
	"\x16ANOMALY_METHOD_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16ANOMALY_METHOD_Z_SCORE\x10\x01\x12\x16\n" +
	"\x12ANOMALY_METHOD_MAD\x10\x02\x12\x16\n" +
	"\x12ANOMALY_METHOD_IQR\x10\x03\x12#\n" +
	"\x1fANOMALY_METHOD_ISOLATION_FOREST\x10\x04*v\n" +
	"\n" +
	"RateWindow\x12\x17\n" +
	"\x13RATE_WINDOW_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eRATE_WINDOW_1M\x10\x01\x12\x12\n" +
	"\x0eRATE_WINDOW_5M\x10\x02\x12\x13\n" +
	"\x0fRATE_WINDOW_15M\x10\x03\x12\x12\n" +
	"\x0eRATE_WINDOW_1H\x10\x04*|\n" +
	"\x0fLogicalOperator\x12\x1c\n" +
	"\x18LOGICAL_OPERATOR_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14LOGICAL_OPERATOR_AND\x10\x01\x12\x17\n" +
	"\x13LOGICAL_OPERATOR_OR\x10\x02\x12\x18\n" +
	"\x14LOGICAL_OPERATOR_NOT\x10\x032\xa2\x06\n" +
	"\fAlertService\x12R\n" +
	"\rEvaluateRules\x12\x1f.api.proto.EvaluateRulesRequest\x1a .api.proto.EvaluateRulesResponse\x128\n" +
	"\bGetAlert\x12\x1a.api.proto.GetAlertRequest\x1a\x10.api.proto.Alert\x12I\n" +
	"\n" +
	"ListAlerts\x12\x1c.api.proto.ListAlertsRequest\x1a\x1d.api.proto.ListAlertsResponse\x12[\n" +
	"\x10AcknowledgeAlert\x12\".api.proto.AcknowledgeAlertRequest\x1a#.api.proto.AcknowledgeAlertResponse\x12O\n" +
	"\fResolveAlert\x12\x1e.api.proto.ResolveAlertRequest\x1a\x1f.api.proto.ResolveAlertResponse\x12B\n" +
	"\fStreamAlerts\x12\x1e.api.proto.StreamAlertsRequest\x1a\x10.api.proto.Alert0\x01\x12J\n" +
	"\x0fCreateAlertRule\x12!.api.proto.CreateAlertRuleRequest\x1a\x14.api.proto.AlertRule\x12J\n" +
	"\x0fUpdateAlertRule\x12!.api.proto.UpdateAlertRuleRequest\x1a\x14.api.proto.AlertRule\x12X\n" +
	"\x0fDeleteAlertRule\x12!.api.proto.DeleteAlertRuleRequest\x1a\".api.proto.DeleteAlertRuleResponse\x12U\n" +
	"\x0eListAlertRules\x12 .api.proto.ListAlertRulesRequest\x1a!.api.proto.ListAlertRulesResponseB7Z5github.com/jfang2048/ai_sre_agent_pub/pkg/proto;protob\x06proto3"

var (
	file_alerting_proto_rawDescOnce sync.Once
	file_alerting_proto_rawDescData []byte
)

func file_alerting_proto_rawDescGZIP() []byte {
	file_alerting_proto_rawDescOnce.Do(func() {
		file_alerting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alerting_proto_rawDesc), len(file_alerting_proto_rawDesc)))
	})
	return file_alerting_proto_rawDescData
}

var file_alerting_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_alerting_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_alerting_proto_goTypes = []any{
	(AlertState)(0),                  // 0: api.proto.AlertState
	(ConditionType)(0),               // 1: api.proto.ConditionType
	(ThresholdOperator)(0),           // 2: api.proto.ThresholdOperator
	(AnomalyMethod)(0),               // 3: api.proto.AnomalyMethod
	(RateWindow)(0),                  // 4: api.proto.RateWindow
	(LogicalOperator)(0),             // 5: api.proto.LogicalOperator
	(*Alert)(nil),                    // 6: api.proto.Alert
	(*MetricReference)(nil),          // 7: api.proto.MetricReference
	(*EventReference)(nil),           // 8: api.proto.EventReference
	(*CorrelationInfo)(nil),          // 9: api.proto.CorrelationInfo
	(*SLOContext)(nil),               // 10: api.proto.SLOContext
	(*AlertRule)(nil),                // 11: api.proto.AlertRule
	(*Condition)(nil),                // 12: api.proto.Condition
	(*ThresholdCondition)(nil),       // 13: api.proto.ThresholdCondition
	(*PredictionCondition)(nil),      // 14: api.proto.PredictionCondition
	(*AnomalyCondition)(nil),         // 15: api.proto.AnomalyCondition
	(*RateCondition)(nil),            // 16: api.proto.RateCondition
	(*CompositeCondition)(nil),       // 17: api.proto.CompositeCondition
	(*SuppressionConfig)(nil),        // 18: api.proto.SuppressionConfig
	(*AlertNotification)(nil),        // 19: api.proto.AlertNotification
	(*NotificationChannel)(nil),      // 20: api.proto.NotificationChannel
	(*EvaluateRulesRequest)(nil),     // 21: api.proto.EvaluateRulesRequest
	(*EvaluateRulesResponse)(nil),    // 22: api.proto.EvaluateRulesResponse
	(*GetAlertRequest)(nil),          // 23: api.proto.GetAlertRequest
	(*ListAlertsRequest)(nil),        // 24: api.proto.ListAlertsRequest
	(*ListAlertsResponse)(nil),       // 25: api.proto.ListAlertsResponse
	(*AcknowledgeAlertRequest)(nil),  // 26: api.proto.AcknowledgeAlertRequest
	(*AcknowledgeAlertResponse)(nil), // 27: api.proto.AcknowledgeAlertResponse
	(*ResolveAlertRequest)(nil),      // 28: api.proto.ResolveAlertRequest
	(*ResolveAlertResponse)(nil),     // 29: api.proto.ResolveAlertResponse
	(*StreamAlertsRequest)(nil),      // 30: api.proto.StreamAlertsRequest
	(*CreateAlertRuleRequest)(nil),   // 31: api.proto.CreateAlertRuleRequest
	(*UpdateAlertRuleRequest)(nil),   // 32: api.proto.UpdateAlertRuleRequest
	(*DeleteAlertRuleRequest)(nil),   // 33: api.proto.DeleteAlertRuleRequest
	(*DeleteAlertRuleResponse)(nil),  // 34: api.proto.DeleteAlertRuleResponse
	(*ListAlertRulesRequest)(nil),    // 35: api.proto.ListAlertRulesRequest
	(*ListAlertRulesResponse)(nil),   // 36: api.proto.ListAlertRulesResponse
	nil,                              // 37: api.proto.Alert.LabelsEntry
	nil,                              // 38: api.proto.Alert.AnnotationsEntry
	nil,                              // 39: api.proto.MetricReference.LabelsEntry
	nil,                              // 40: api.proto.AlertRule.LabelsEntry
	nil,                              // 41: api.proto.AlertRule.AnnotationsEntry
	nil,                              // 42: api.proto.NotificationChannel.ConfigEntry
	nil,                              // 43: api.proto.ListAlertsRequest.LabelMatcherEntry
	nil,                              // 44: api.proto.StreamAlertsRequest.LabelMatcherEntry
	(Severity)(0),                    // 45: api.proto.Severity
	(*timestamppb.Timestamp)(nil),    // 46: google.protobuf.Timestamp
}
var file_alerting_proto_depIdxs = []int32{
	45, // 0: api.proto.Alert.severity:type_name -> api.proto.Severity
	0,  // 1: api.proto.Alert.state:type_name -> api.proto.AlertState
	46, // 2: api.proto.Alert.created_at:type_name -> google.protobuf.Timestamp
	46, // 3: api.proto.Alert.updated_at:type_name -> google.protobuf.Timestamp
	46, // 4: api.proto.Alert.resolved_at:type_name -> google.protobuf.Timestamp
	37, // 5: api.proto.Alert.labels:type_name -> api.proto.Alert.LabelsEntry
	38, // 6: api.proto.Alert.annotations:type_name -> api.proto.Alert.AnnotationsEntry
	7,  // 7: api.proto.Alert.metrics:type_name -> api.proto.MetricReference
	8,  // 8: api.proto.Alert.events:type_name -> api.proto.EventReference
	9,  // 9: api.proto.Alert.correlation:type_name -> api.proto.CorrelationInfo
	10, // 10: api.proto.Alert.slo_context:type_name -> api.proto.SLOContext
	46, // 11: api.proto.MetricReference.timestamp:type_name -> google.protobuf.Timestamp
	39, // 12: api.proto.MetricReference.labels:type_name -> api.proto.MetricReference.LabelsEntry
	46, // 13: api.proto.EventReference.timestamp:type_name -> google.protobuf.Timestamp
	12, // 14: api.proto.AlertRule.condition:type_name -> api.proto.Condition
	45, // 15: api.proto.AlertRule.severity:type_name -> api.proto.Severity
	40, // 16: api.proto.AlertRule.labels:type_name -> api.proto.AlertRule.LabelsEntry
	41, // 17: api.proto.AlertRule.annotations:type_name -> api.proto.AlertRule.AnnotationsEntry
	18, // 18: api.proto.AlertRule.suppression:type_name -> api.proto.SuppressionConfig
	1,  // 19: api.proto.Condition.type:type_name -> api.proto.ConditionType
	13, // 20: api.proto.Condition.threshold:type_name -> api.proto.ThresholdCondition
	14, // 21: api.proto.Condition.prediction:type_name -> api.proto.PredictionCondition
	15, // 22: api.proto.Condition.anomaly:type_name -> api.proto.AnomalyCondition
	16, // 23: api.proto.Condition.rate:type_name -> api.proto.RateCondition
	17, // 24: api.proto.Condition.composite:type_name -> api.proto.CompositeCondition
	2,  // 25: api.proto.ThresholdCondition.operator:type_name -> api.proto.ThresholdOperator
	3,  // 26: api.proto.AnomalyCondition.method:type_name -> api.proto.AnomalyMethod
	4,  // 27: api.proto.RateCondition.window:type_name -> api.proto.RateWindow
	12, // 28: api.proto.CompositeCondition.conditions:type_name -> api.proto.Condition
	5,  // 29: api.proto.CompositeCondition.operator:type_name -> api.proto.LogicalOperator
	46, // 30: api.proto.AlertNotification.sent_at:type_name -> google.protobuf.Timestamp
	42, // 31: api.proto.NotificationChannel.config:type_name -> api.proto.NotificationChannel.ConfigEntry
	45, // 32: api.proto.NotificationChannel.accepted_severities:type_name -> api.proto.Severity
	6,  // 33: api.proto.EvaluateRulesResponse.alerts:type_name -> api.proto.Alert
	46, // 34: api.proto.ListAlertsRequest.start_time:type_name -> google.protobuf.Timestamp
	46, // 35: api.proto.ListAlertsRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 36: api.proto.ListAlertsRequest.states:type_name -> api.proto.AlertState
	45, // 37: api.proto.ListAlertsRequest.severities:type_name -> api.proto.Severity
	43, // 38: api.proto.ListAlertsRequest.label_matcher:type_name -> api.proto.ListAlertsRequest.LabelMatcherEntry
	6,  // 39: api.proto.ListAlertsResponse.alerts:type_name -> api.proto.Alert
	45, // 40: api.proto.StreamAlertsRequest.min_severity:type_name -> api.proto.Severity
	44, // 41: api.proto.StreamAlertsRequest.label_matcher:type_name -> api.proto.StreamAlertsRequest.LabelMatcherEntry
	11, // 42: api.proto.CreateAlertRuleRequest.rule:type_name -> api.proto.AlertRule
	11, // 43: api.proto.UpdateAlertRuleRequest.rule:type_name -> api.proto.AlertRule
	11, // 44: api.proto.ListAlertRulesResponse.rules:type_name -> api.proto.AlertRule
	21, // 45: api.proto.AlertService.EvaluateRules:input_type -> api.proto.EvaluateRulesRequest
	23, // 46: api.proto.AlertService.GetAlert:input_type -> api.proto.GetAlertRequest
	24, // 47: api.proto.AlertService.ListAlerts:input_type -> api.proto.ListAlertsRequest
	26, // 48: api.proto.AlertService.AcknowledgeAlert:input_type -> api.proto.AcknowledgeAlertRequest
	28, // 49: api.proto.AlertService.ResolveAlert:input_type -> api.proto.ResolveAlertRequest
	30, // 50: api.proto.AlertService.StreamAlerts:input_type -> api.proto.StreamAlertsRequest
	31, // 51: api.proto.AlertService.CreateAlertRule:input_type -> api.proto.CreateAlertRuleRequest
	32, // 52: api.proto.AlertService.UpdateAlertRule:input_type -> api.proto.UpdateAlertRuleRequest
	33, // 53: api.proto.AlertService.DeleteAlertRule:input_type -> api.proto.DeleteAlertRuleRequest
	35, // 54: api.proto.AlertService.ListAlertRules:input_type -> api.proto.ListAlertRulesRequest
	22, // 55: api.proto.AlertService.EvaluateRules:output_type -> api.proto.EvaluateRulesResponse
	6,  // 56: api.proto.AlertService.GetAlert:output_type -> api.proto.Alert
	25, // 57: api.proto.AlertService.ListAlerts:output_type -> api.proto.ListAlertsResponse
	27, // 58: api.proto.AlertService.AcknowledgeAlert:output_type -> api.proto.AcknowledgeAlertResponse
	29, // 59: api.proto.AlertService.ResolveAlert:output_type -> api.proto.ResolveAlertResponse
	6,  // 60: api.proto.AlertService.StreamAlerts:output_type -> api.proto.Alert
	11, // 61: api.proto.AlertService.CreateAlertRule:output_type -> api.proto.AlertRule
	11, // 62: api.proto.AlertService.UpdateAlertRule:output_type -> api.proto.AlertRule
	34, // 63: api.proto.AlertService.DeleteAlertRule:output_type -> api.proto.DeleteAlertRuleResponse
	36, // 64: api.proto.AlertService.ListAlertRules:output_type -> api.proto.ListAlertRulesResponse
	55, // [55:65] is the sub-list for method output_type
	45, // [45:55] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_alerting_proto_init() }
func file_alerting_proto_init() {
	if File_alerting_proto != nil {
		return
	}
	file_common_proto_init()
	file_alerting_proto_msgTypes[6].OneofWrappers = []any{
		(*Condition_Threshold)(nil),
		(*Condition_Prediction)(nil),
		(*Condition_Anomaly)(nil),
		(*Condition_Rate)(nil),
		(*Condition_Composite)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alerting_proto_rawDesc), len(file_alerting_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alerting_proto_goTypes,
		DependencyIndexes: file_alerting_proto_depIdxs,
		EnumInfos:         file_alerting_proto_enumTypes,
		MessageInfos:      file_alerting_proto_msgTypes,
	}.Build()
	File_alerting_proto = out.File
	file_alerting_proto_goTypes = nil
	file_alerting_proto_depIdxs = nil
}
