// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common Severity levels
type Severity int32

const (
	Severity_SEVERITY_UNKNOWN   Severity = 0
	Severity_SEVERITY_INFO      Severity = 1
	Severity_SEVERITY_WARNING   Severity = 2
	Severity_SEVERITY_ERROR     Severity = 3
	Severity_SEVERITY_CRITICAL  Severity = 4
	Severity_SEVERITY_FATAL     Severity = 5
	Severity_SEVERITY_EMERGENCY Severity = 6
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNKNOWN",
		1: "SEVERITY_INFO",
		2: "SEVERITY_WARNING",
		3: "SEVERITY_ERROR",
		4: "SEVERITY_CRITICAL",
		5: "SEVERITY_FATAL",
		6: "SEVERITY_EMERGENCY",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNKNOWN":   0,
		"SEVERITY_INFO":      1,
		"SEVERITY_WARNING":   2,
		"SEVERITY_ERROR":     3,
		"SEVERITY_CRITICAL":  4,
		"SEVERITY_FATAL":     5,
		"SEVERITY_EMERGENCY": 6,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\tapi.proto*\xa0\x01\n" +
	"\bSeverity\x12\x14\n" +
	"\x10SEVERITY_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x04\x12\x12\n" +
	"\x0eSEVERITY_FATAL\x10\x05\x12\x16\n" +
	"\x12SEVERITY_EMERGENCY\x10\x06B7Z5github.com/jfang2048/ai_sre_agent_pub/pkg/proto;protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_goTypes = []any{
	(Severity)(0), // 0: api.proto.Severity
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
