// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: slo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SLOService_GetSLO_FullMethodName         = "/api.proto.SLOService/GetSLO"
	SLOService_ListSLOs_FullMethodName       = "/api.proto.SLOService/ListSLOs"
	SLOService_CreateSLO_FullMethodName      = "/api.proto.SLOService/CreateSLO"
	SLOService_UpdateSLO_FullMethodName      = "/api.proto.SLOService/UpdateSLO"
	SLOService_DeleteSLO_FullMethodName      = "/api.proto.SLOService/DeleteSLO"
	SLOService_GetSLOStatus_FullMethodName   = "/api.proto.SLOService/GetSLOStatus"
	SLOService_ListSLOStatus_FullMethodName  = "/api.proto.SLOService/ListSLOStatus"
	SLOService_GetSLIReport_FullMethodName   = "/api.proto.SLOService/GetSLIReport"
	SLOService_WatchSLOStatus_FullMethodName = "/api.proto.SLOService/WatchSLOStatus"
)

// SLOServiceClient is the client API for SLOService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SLOService manages SLOs
type SLOServiceClient interface {
	// Get a single SLO
	GetSLO(ctx context.Context, in *GetSLORequest, opts ...grpc.CallOption) (*GetSLOResponse, error)
	// List all SLOs
	ListSLOs(ctx context.Context, in *ListSLOsRequest, opts ...grpc.CallOption) (*ListSLOsResponse, error)
	// Create a new SLO
	CreateSLO(ctx context.Context, in *CreateSLORequest, opts ...grpc.CallOption) (*CreateSLOResponse, error)
	// Update an existing SLO
	UpdateSLO(ctx context.Context, in *UpdateSLORequest, opts ...grpc.CallOption) (*UpdateSLOResponse, error)
	// Delete an SLO
	DeleteSLO(ctx context.Context, in *DeleteSLORequest, opts ...grpc.CallOption) (*DeleteSLOResponse, error)
	// Get current SLO status
	GetSLOStatus(ctx context.Context, in *GetSLOStatusRequest, opts ...grpc.CallOption) (*GetSLOStatusResponse, error)
	// List multiple SLO statuses
	ListSLOStatus(ctx context.Context, in *ListSLOStatusRequest, opts ...grpc.CallOption) (*ListSLOStatusResponse, error)
	// Get detailed SLI report
	GetSLIReport(ctx context.Context, in *GetSLIReportRequest, opts ...grpc.CallOption) (*GetSLIReportResponse, error)
	// Stream SLO status updates
	WatchSLOStatus(ctx context.Context, in *WatchSLOStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SLOStatus], error)
}

type sLOServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSLOServiceClient(cc grpc.ClientConnInterface) SLOServiceClient {
	return &sLOServiceClient{cc}
}

func (c *sLOServiceClient) GetSLO(ctx context.Context, in *GetSLORequest, opts ...grpc.CallOption) (*GetSLOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSLOResponse)
	err := c.cc.Invoke(ctx, SLOService_GetSLO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sLOServiceClient) ListSLOs(ctx context.Context, in *ListSLOsRequest, opts ...grpc.CallOption) (*ListSLOsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSLOsResponse)
	err := c.cc.Invoke(ctx, SLOService_ListSLOs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sLOServiceClient) CreateSLO(ctx context.Context, in *CreateSLORequest, opts ...grpc.CallOption) (*CreateSLOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSLOResponse)
	err := c.cc.Invoke(ctx, SLOService_CreateSLO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sLOServiceClient) UpdateSLO(ctx context.Context, in *UpdateSLORequest, opts ...grpc.CallOption) (*UpdateSLOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSLOResponse)
	err := c.cc.Invoke(ctx, SLOService_UpdateSLO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sLOServiceClient) DeleteSLO(ctx context.Context, in *DeleteSLORequest, opts ...grpc.CallOption) (*DeleteSLOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSLOResponse)
	err := c.cc.Invoke(ctx, SLOService_DeleteSLO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sLOServiceClient) GetSLOStatus(ctx context.Context, in *GetSLOStatusRequest, opts ...grpc.CallOption) (*GetSLOStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSLOStatusResponse)
	err := c.cc.Invoke(ctx, SLOService_GetSLOStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sLOServiceClient) ListSLOStatus(ctx context.Context, in *ListSLOStatusRequest, opts ...grpc.CallOption) (*ListSLOStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSLOStatusResponse)
	err := c.cc.Invoke(ctx, SLOService_ListSLOStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sLOServiceClient) GetSLIReport(ctx context.Context, in *GetSLIReportRequest, opts ...grpc.CallOption) (*GetSLIReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSLIReportResponse)
	err := c.cc.Invoke(ctx, SLOService_GetSLIReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sLOServiceClient) WatchSLOStatus(ctx context.Context, in *WatchSLOStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SLOStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SLOService_ServiceDesc.Streams[0], SLOService_WatchSLOStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchSLOStatusRequest, SLOStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SLOService_WatchSLOStatusClient = grpc.ServerStreamingClient[SLOStatus]

// SLOServiceServer is the server API for SLOService service.
// All implementations must embed UnimplementedSLOServiceServer
// for forward compatibility.
//
// SLOService manages SLOs
type SLOServiceServer interface {
	// Get a single SLO
	GetSLO(context.Context, *GetSLORequest) (*GetSLOResponse, error)
	// List all SLOs
	ListSLOs(context.Context, *ListSLOsRequest) (*ListSLOsResponse, error)
	// Create a new SLO
	CreateSLO(context.Context, *CreateSLORequest) (*CreateSLOResponse, error)
	// Update an existing SLO
	UpdateSLO(context.Context, *UpdateSLORequest) (*UpdateSLOResponse, error)
	// Delete an SLO
	DeleteSLO(context.Context, *DeleteSLORequest) (*DeleteSLOResponse, error)
	// Get current SLO status
	GetSLOStatus(context.Context, *GetSLOStatusRequest) (*GetSLOStatusResponse, error)
	// List multiple SLO statuses
	ListSLOStatus(context.Context, *ListSLOStatusRequest) (*ListSLOStatusResponse, error)
	// Get detailed SLI report
	GetSLIReport(context.Context, *GetSLIReportRequest) (*GetSLIReportResponse, error)
	// Stream SLO status updates
	WatchSLOStatus(*WatchSLOStatusRequest, grpc.ServerStreamingServer[SLOStatus]) error
	mustEmbedUnimplementedSLOServiceServer()
}

// UnimplementedSLOServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSLOServiceServer struct{}

func (UnimplementedSLOServiceServer) GetSLO(context.Context, *GetSLORequest) (*GetSLOResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSLO not implemented")
}
func (UnimplementedSLOServiceServer) ListSLOs(context.Context, *ListSLOsRequest) (*ListSLOsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSLOs not implemented")
}
func (UnimplementedSLOServiceServer) CreateSLO(context.Context, *CreateSLORequest) (*CreateSLOResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSLO not implemented")
}
func (UnimplementedSLOServiceServer) UpdateSLO(context.Context, *UpdateSLORequest) (*UpdateSLOResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSLO not implemented")
}
func (UnimplementedSLOServiceServer) DeleteSLO(context.Context, *DeleteSLORequest) (*DeleteSLOResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSLO not implemented")
}
func (UnimplementedSLOServiceServer) GetSLOStatus(context.Context, *GetSLOStatusRequest) (*GetSLOStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSLOStatus not implemented")
}
func (UnimplementedSLOServiceServer) ListSLOStatus(context.Context, *ListSLOStatusRequest) (*ListSLOStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSLOStatus not implemented")
}
func (UnimplementedSLOServiceServer) GetSLIReport(context.Context, *GetSLIReportRequest) (*GetSLIReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSLIReport not implemented")
}
func (UnimplementedSLOServiceServer) WatchSLOStatus(*WatchSLOStatusRequest, grpc.ServerStreamingServer[SLOStatus]) error {
	return status.Error(codes.Unimplemented, "method WatchSLOStatus not implemented")
}
func (UnimplementedSLOServiceServer) mustEmbedUnimplementedSLOServiceServer() {}
func (UnimplementedSLOServiceServer) testEmbeddedByValue()                    {}

// UnsafeSLOServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SLOServiceServer will
// result in compilation errors.
type UnsafeSLOServiceServer interface {
	mustEmbedUnimplementedSLOServiceServer()
}

func RegisterSLOServiceServer(s grpc.ServiceRegistrar, srv SLOServiceServer) {
	// If the following call panics, it indicates UnimplementedSLOServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SLOService_ServiceDesc, srv)
}

func _SLOService_GetSLO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSLORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SLOServiceServer).GetSLO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SLOService_GetSLO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SLOServiceServer).GetSLO(ctx, req.(*GetSLORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SLOService_ListSLOs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSLOsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SLOServiceServer).ListSLOs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SLOService_ListSLOs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SLOServiceServer).ListSLOs(ctx, req.(*ListSLOsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SLOService_CreateSLO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSLORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SLOServiceServer).CreateSLO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SLOService_CreateSLO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SLOServiceServer).CreateSLO(ctx, req.(*CreateSLORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SLOService_UpdateSLO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSLORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SLOServiceServer).UpdateSLO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SLOService_UpdateSLO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SLOServiceServer).UpdateSLO(ctx, req.(*UpdateSLORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SLOService_DeleteSLO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSLORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SLOServiceServer).DeleteSLO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SLOService_DeleteSLO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SLOServiceServer).DeleteSLO(ctx, req.(*DeleteSLORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SLOService_GetSLOStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSLOStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SLOServiceServer).GetSLOStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SLOService_GetSLOStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SLOServiceServer).GetSLOStatus(ctx, req.(*GetSLOStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SLOService_ListSLOStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSLOStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SLOServiceServer).ListSLOStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SLOService_ListSLOStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SLOServiceServer).ListSLOStatus(ctx, req.(*ListSLOStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SLOService_GetSLIReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSLIReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SLOServiceServer).GetSLIReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SLOService_GetSLIReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SLOServiceServer).GetSLIReport(ctx, req.(*GetSLIReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SLOService_WatchSLOStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchSLOStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SLOServiceServer).WatchSLOStatus(m, &grpc.GenericServerStream[WatchSLOStatusRequest, SLOStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SLOService_WatchSLOStatusServer = grpc.ServerStreamingServer[SLOStatus]

// SLOService_ServiceDesc is the grpc.ServiceDesc for SLOService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SLOService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.SLOService",
	HandlerType: (*SLOServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSLO",
			Handler:    _SLOService_GetSLO_Handler,
		},
		{
			MethodName: "ListSLOs",
			Handler:    _SLOService_ListSLOs_Handler,
		},
		{
			MethodName: "CreateSLO",
			Handler:    _SLOService_CreateSLO_Handler,
		},
		{
			MethodName: "UpdateSLO",
			Handler:    _SLOService_UpdateSLO_Handler,
		},
		{
			MethodName: "DeleteSLO",
			Handler:    _SLOService_DeleteSLO_Handler,
		},
		{
			MethodName: "GetSLOStatus",
			Handler:    _SLOService_GetSLOStatus_Handler,
		},
		{
			MethodName: "ListSLOStatus",
			Handler:    _SLOService_ListSLOStatus_Handler,
		},
		{
			MethodName: "GetSLIReport",
			Handler:    _SLOService_GetSLIReport_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchSLOStatus",
			Handler:       _SLOService_WatchSLOStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "slo.proto",
}
